#### Exploratory Data Analysis
After the cleanup process, I decided to explore the data more to spot any interesting trends and patterns that could help build a better understanding of the data presented and potentially help in building a more effective predictive model

I decided to formulate a few key questions for this process. The Questions are as follows:

1.) Which fighting stances appear to possibly have an advantage/disadvantage over other stances. Answering this question will involve looking at fights involving boxers with different fighting stances and recording the percentage of wins over other stances for each fighting stance.

2.) What are the ideal body dimensions for an elite boxer in each weight division, has this ideal changed over the last few decades. For this, I will focus on fighters who are in the top 10% in terms of wins and win rate in each division and look for patterns in height and weight and fighting stance

3.) Who are the top 2 boxers in each division who have managed to beat opponents that weight significantly more than they do and how have these victories come (knockouts v points)

4.)

In [5]:
#requirements
# pip install bokeh

Collecting dash
  Downloading https://files.pythonhosted.org/packages/03/f4/d27b82bc85d2e7834d478ff5598bdfcc1835ec10723c79e0239dadee6dfd/dash-1.6.1.tar.gz (61kB)
Collecting Flask>=1.0.2
  Downloading https://files.pythonhosted.org/packages/9b/93/628509b8d5dc749656a9641f4caf13540e2cdec85276964ff8f43bbb1d3b/Flask-1.1.1-py2.py3-none-any.whl (94kB)
Collecting flask-compress
  Downloading https://files.pythonhosted.org/packages/0e/2a/378bd072928f6d92fd8c417d66b00c757dc361c0405a46a0134de6fd323d/Flask-Compress-1.4.0.tar.gz
Requirement already satisfied: plotly in c:\users\user\anaconda3\lib\site-packages (from dash) (4.2.1)
Collecting dash_renderer==1.2.1
  Downloading https://files.pythonhosted.org/packages/18/a4/30092f83b7a7c39dfc3c03aa4a4065566194155714393bfdfa26ae01b0a8/dash_renderer-1.2.1.tar.gz (1.1MB)
Collecting dash-core-components==1.5.1
  Downloading https://files.pythonhosted.org/packages/e4/60/4beeb7d66b43a60a3e349eec9b20b6db85f5657664f015e03a49b25d5e92/dash_core_components-1.5.1.tar.gz (5.1MB)
Collecting dash-html-components==1.0.2
  Downloading https://files.pythonhosted.org/packages/b4/9e/76988b02d09268495218639ad45dbfafe7dec8a52961278aeedaffb638ea/dash_html_components-1.0.2.tar.gz (187kB)
Collecting dash-table==4.5.1
  Downloading https://files.pythonhosted.org/packages/17/3b/955732356f7078feb4fbae38a9eb971fa55278cc31310c8ae1f0186f1b10/dash_table-4.5.1.tar.gz (1.7MB)
Requirement already satisfied: future in c:\users\user\anaconda3\lib\site-packages (from dash) (0.17.1)
Collecting itsdangerous>=0.24
  Downloading https://files.pythonhosted.org/packages/76/ae/44b03b253d6fade317f32c24d100b3b35c2239807046a4c953c7b89fa49e/itsdangerous-1.1.0-py2.py3-none-any.whl
Collecting Werkzeug>=0.15
  Downloading https://files.pythonhosted.org/packages/ce/42/3aeda98f96e85fd26180534d36570e4d18108d62ae36f87694b476b83d6f/Werkzeug-0.16.0-py2.py3-none-any.whl (327kB)
Requirement already satisfied: Jinja2>=2.10.1 in c:\users\user\anaconda3\lib\site-packages (from Flask>=1.0.2->dash) (2.10.3)
Requirement already satisfied: click>=5.1 in c:\users\user\anaconda3\lib\site-packages (from Flask>=1.0.2->dash) (7.0)
Requirement already satisfied: retrying>=1.3.3 in c:\users\user\anaconda3\lib\site-packages (from plotly->dash) (1.3.3)
Requirement already satisfied: six in c:\users\user\anaconda3\lib\site-packages (from plotly->dash) (1.12.0)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\user\anaconda3\lib\site-packages (from Jinja2>=2.10.1->Flask>=1.0.2->dash) (1.1.1)
Building wheels for collected packages: dash, flask-compress, dash-renderer, dash-core-components, dash-html-components, dash-table
  Building wheel for dash (setup.py): started
  Building wheel for dash (setup.py): finished with status 'done'
  Created wheel for dash: filename=dash-1.6.1-cp37-none-any.whl size=68685 sha256=98e928d73616ef2129c6421d6660a6277230cd5e2aa420b4bcce18db84ba0da8
  Stored in directory: C:\Users\User\AppData\Local\pip\Cache\wheels\06\0e\ba\d4c1039566a4976366af6c665f8f4b2cb1dde700b48e33f1c0
  Building wheel for flask-compress (setup.py): started
  Building wheel for flask-compress (setup.py): finished with status 'done'
  Created wheel for flask-compress: filename=Flask_Compress-1.4.0-cp37-none-any.whl size=3716 sha256=63061ce2eebb93a437aefda2fdf62f4a47c46e47d97b37c0a012a9419378d34b
  Stored in directory: C:\Users\User\AppData\Local\pip\Cache\wheels\96\32\88\a1f6d9dd3c29570ab3a8acc0d556b3b20abcf3c623c868ce0a
  Building wheel for dash-renderer (setup.py): started
  Building wheel for dash-renderer (setup.py): finished with status 'done'
  Created wheel for dash-renderer: filename=dash_renderer-1.2.1-cp37-none-any.whl size=1149056 sha256=ce9efa2ff5dde64e452581f5f2e87fb464c0fcd95a1fa6f241ad09d9b3a062dd
  Stored in directory: C:\Users\User\AppData\Local\pip\Cache\wheels\cb\24\20\00e8368c63443f648712bd891aa55c43bd21a14eccd7319393
  Building wheel for dash-core-components (setup.py): started
  Building wheel for dash-core-components (setup.py): finished with status 'done'
  Created wheel for dash-core-components: filename=dash_core_components-1.5.1-cp37-none-any.whl size=5199664 sha256=2db658ee40c91898ac1e280b71e6c28671adc115a0b1b7139b58f329cdc48cd3
  Stored in directory: C:\Users\User\AppData\Local\pip\Cache\wheels\3d\6f\52\81af3eff649d4468c49b5230633cc27b77386e9bda24bb3b69
  Building wheel for dash-html-components (setup.py): started
  Building wheel for dash-html-components (setup.py): finished with status 'done'
  Created wheel for dash-html-components: filename=dash_html_components-1.0.2-cp37-none-any.whl size=427909 sha256=5ff61a41e5527b08a9023c59c138b983907747b3cc9974d3ef90cdcea52c634d
  Stored in directory: C:\Users\User\AppData\Local\pip\Cache\wheels\59\6d\79\e8fbded6c6102c00ef0d58a278a488d913d30c51ae95dbef90
  Building wheel for dash-table (setup.py): started
  Building wheel for dash-table (setup.py): finished with status 'done'
  Created wheel for dash-table: filename=dash_table-4.5.1-cp37-none-any.whl size=1702916 sha256=977bf1e191334eaabcf66bf5394554d43b698179504558938e6fab97b6078e30
  Stored in directory: C:\Users\User\AppData\Local\pip\Cache\wheels\6e\b7\10\5eb393a55845cd2df31d66329b5bc0894e930527165e174059
Successfully built dash flask-compress dash-renderer dash-core-components dash-html-components dash-table
Installing collected packages: itsdangerous, Werkzeug, Flask, flask-compress, dash-renderer, dash-core-components, dash-html-components, dash-table, dash
Successfully installed Flask-1.1.1 Werkzeug-0.16.0 dash-1.6.1 dash-core-components-1.5.1 dash-html-components-1.0.2 dash-renderer-1.2.1 dash-table-4.5.1 flask-compress-1.4.0 itsdangerous-1.1.0
Note: you may need to restart the kernel to use updated packages.

In [2]:
import dash
import dash_core_components as dcc
import dash_html_components as html
import plotly.graph_objs as go
import dateutil
import pandas as pd 
import os

In [5]:
data = pd.read_csv('C:\\Users\\User\\Documents\\visuals.csv')
data['bouts_fought'] = data['w'].astype('float')+data['l'].astype('float')+data['d'].astype('float')

C:\Users\User\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning:

Columns (682,685,699,702,716,719,733,736,744,745,747,748,749,750,751,752,753,754,755,756,757,758,760,761,762,764,765,766,767,768,769,770,771,772,773,774,775,777,778,779,781,782,783,784,785,786,787,788,789,790,791,792,794,795,796,798,799,800,801,802,803,804,805,806,807,808,809,811,812,813,815,816,817,818,819,820,821,822,823,824,825,826,828,829,830,832,833,834,835,836,837,838,839,840,841,842,843,845,846,847,849,850,851,852,853,854,855,856,857,858,859,860,862,863,864,866,867,868,869,870,871,872,873,874,875,876,877,879,880,881,883,884,885,886,887,888,889,890,891,892,893,894,896,897,898,900,901,902,903,904,905,906,907,908,909,910,911,913,914,915,917,918,919,920,921,922,923,924,925,926,927,928,930,931,932,934,935,936,937,938,939,940,941,942,943,944,945,947,948,949,951,952,953,954,955,956,957,958,959,960,961,962,964,965,966,968,969,970,971,972,973,974,975,976,977,978,979,981,982,983,985,986,987,988,989,990,991,992,993,994,995,996,998,999,1000,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1015,1016,1017,1019,1020,1021,1022,1023,1024,1025,1026,1027,1028,1029,1030,1032,1033,1034,1036,1037,1038,1039,1040,1041,1042,1043,1044,1045,1046,1047,1049,1050,1051,1053,1054,1055,1056,1057,1058,1060,1061,1062,1063,1064,1066,1067,1068,1070,1071,1072,1074,1075,1077,1078,1079,1080,1081,1083,1084,1085,1087,1088,1089,1091,1092,1094,1095,1096,1097,1098,1100,1101,1102,1104,1105,1106,1108,1109,1111,1112,1113,1114,1115,1117,1118,1119,1121,1122,1123,1125,1126,1128,1129,1130,1131,1132,1134,1135,1136,1138,1139,1140,1141,1142,1143,1145,1146,1147,1148,1149,1151,1152,1153,1155,1156,1157,1159,1160,1162,1163,1164,1165,1166,1168,1169,1170,1172,1173,1174,1175,1176,1177,1179,1180,1181,1182,1183,1185,1186,1187,1189,1190,1191,1192,1193,1194,1196,1197,1198,1199,1200,1202,1203,1204,1206,1207,1208,1210,1211,1213,1214,1215,1216,1217,1219,1220,1221,1223,1224,1225,1226,1227,1228,1230,1231,1232,1233,1234,1236,1237,1238,1240,1241,1242,1243,1244,1245,1247,1248,1249,1250,1251,1253,1254,1255,1257,1258,1259,1261,1262,1264,1265,1266,1267,1268,1270,1271,1272,1274,1275,1276,1278,1279,1281,1282,1283,1284,1285,1287,1441,1442,1443,1444,1445,1446,1447,1448,1449,1450,1451,1452,1453,1454,1455,1456,1457,1458,1459,1460,1461,1462,1463,1464,1465,1466,1467,1468,1469,1470,1471,1472,1473,1474,1475,1476,1477,1478,1479,1480,1481,1482,1483,1484,1485,1486,1487,1488,1489,1490,1491,1492,1493,1494,1495,1496,1497,1498,1499,1500,1501,1502,1503,1504,1505,1506,1507,1508,1509,1510,1511,1512,1513,1514,1515,1516,1517,1518,1519,1520,1521,1522,1523,1524,1525,1526,1527,1528,1529,1530,1531,1532,1533,1534,1535,1536,1537,1538,1539,1540,1541,1542,1543,1544,1545,1546,1547,1548,1549,1550,1551,1552,1553,1554,1555,1556,1557,1558,1559,1560,1561,1562,1563,1564,1565,1566,1567,1568,1569,1570,1571,1572,1573,1574,1575,1576,1577,1578,1579,1580,1581,1582,1583,1584,1585,1586,1587,1588,1589,1590,1591,1592,1593,1594,1595,1596,1597,1598,1599,1600,1601,1602,1603,1604,1605,1606,1607,1608,1609,1610,1611,1612,1613,1614,1615,1616,1617,1618,1619,1620,1621,1622,1623,1624,1625,1626,1627,1628,1629,1630,1631,1632,1633,1634,1635,1636,1637,1638,1639,1640,1641,1642,1643,1644,1645,1646,1647,1648,1649,1650,1651,1652,1653,1654,1655,1656,1657,1658,1659,1660,1661,1662,1663,1664,1665,1666,1667,1668,1669,1670,1671,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682,1683,1684,1685,1686,1687,1688,1689,1690,1691,1692,1693,1694,1695) have mixed types. Specify dtype option on import or set low_memory=False.

In [6]:
data['outcome2'].str.extract('([a-zA-Z]+)')
#iterate through fight stances 
list(data)

['Unnamed: 0',
 'miles',
 'location',
 'name',
 'sex',
 'w',
 'l',
 'd',
 'division',
 'from',
 'to',
 'players_links',
 'global_id',
 'date1',
 'firstBoxerRating1',
 'firstBoxerWeight1',
 'JudgeID1',
 'Links1',
 'location1',
 'metadata1',
 'numberofrounds1',
 'outcome1',
 'rating1',
 'referee1',
 'secondBoxer1',
 'secondBoxerLast61',
 'secondBoxerRating1',
 'secondBoxerRecord1',
 'secondBoxerWeight1',
 'titles1',
 'date2',
 'firstBoxerRating2',
 'firstBoxerWeight2',
 'JudgeID2',
 'Links2',
 'location2',
 'metadata2',
 'numberofrounds2',
 'outcome2',
 'rating2',
 'referee2',
 'secondBoxer2',
 'secondBoxerLast62',
 'secondBoxerRating2',
 'secondBoxerRecord2',
 'secondBoxerWeight2',
 'titles2',
 'date3',
 'firstBoxerRating3',
 'firstBoxerWeight3',
 'JudgeID3',
 'Links3',
 'location3',
 'metadata3',
 'numberofrounds3',
 'outcome3',
 'rating3',
 'referee3',
 'secondBoxer3',
 'secondBoxerLast63',
 'secondBoxerRating3',
 'secondBoxerRecord3',
 'secondBoxerWeight3',
 'titles3',
 'date4',
 'firstBoxerRating4',
 'firstBoxerWeight4',
 'JudgeID4',
 'Links4',
 'location4',
 'metadata4',
 'numberofrounds4',
 'outcome4',
 'rating4',
 'referee4',
 'secondBoxer4',
 'secondBoxerLast64',
 'secondBoxerRating4',
 'secondBoxerRecord4',
 'secondBoxerWeight4',
 'titles4',
 'date5',
 'firstBoxerRating5',
 'firstBoxerWeight5',
 'JudgeID5',
 'Links5',
 'location5',
 'metadata5',
 'numberofrounds5',
 'outcome5',
 'rating5',
 'referee5',
 'secondBoxer5',
 'secondBoxerLast65',
 'secondBoxerRating5',
 'secondBoxerRecord5',
 'secondBoxerWeight5',
 'titles5',
 'date6',
 'firstBoxerRating6',
 'firstBoxerWeight6',
 'JudgeID6',
 'Links6',
 'location6',
 'metadata6',
 'numberofrounds6',
 'outcome6',
 'rating6',
 'referee6',
 'secondBoxer6',
 'secondBoxerLast66',
 'secondBoxerRating6',
 'secondBoxerRecord6',
 'secondBoxerWeight6',
 'titles6',
 'date7',
 'firstBoxerRating7',
 'firstBoxerWeight7',
 'JudgeID7',
 'Links7',
 'location7',
 'metadata7',
 'numberofrounds7',
 'outcome7',
 'rating7',
 'referee7',
 'secondBoxer7',
 'secondBoxerLast67',
 'secondBoxerRating7',
 'secondBoxerRecord7',
 'secondBoxerWeight7',
 'titles7',
 'date8',
 'firstBoxerRating8',
 'firstBoxerWeight8',
 'JudgeID8',
 'Links8',
 'location8',
 'metadata8',
 'numberofrounds8',
 'outcome8',
 'rating8',
 'referee8',
 'secondBoxer8',
 'secondBoxerLast68',
 'secondBoxerRating8',
 'secondBoxerRecord8',
 'secondBoxerWeight8',
 'titles8',
 'date9',
 'firstBoxerRating9',
 'firstBoxerWeight9',
 'JudgeID9',
 'Links9',
 'location9',
 'metadata9',
 'numberofrounds9',
 'outcome9',
 'rating9',
 'referee9',
 'secondBoxer9',
 'secondBoxerLast69',
 'secondBoxerRating9',
 'secondBoxerRecord9',
 'secondBoxerWeight9',
 'titles9',
 'date10',
 'firstBoxerRating10',
 'firstBoxerWeight10',
 'JudgeID10',
 'Links10',
 'location10',
 'metadata10',
 'numberofrounds10',
 'outcome10',
 'rating10',
 'referee10',
 'secondBoxer10',
 'secondBoxerLast610',
 'secondBoxerRating10',
 'secondBoxerRecord10',
 'secondBoxerWeight10',
 'titles10',
 'date11',
 'firstBoxerRating11',
 'firstBoxerWeight11',
 'JudgeID11',
 'Links11',
 'location11',
 'metadata11',
 'numberofrounds11',
 'outcome11',
 'rating11',
 'referee11',
 'secondBoxer11',
 'secondBoxerLast611',
 'secondBoxerRating11',
 'secondBoxerRecord11',
 'secondBoxerWeight11',
 'titles11',
 'date12',
 'firstBoxerRating12',
 'firstBoxerWeight12',
 'JudgeID12',
 'Links12',
 'location12',
 'metadata12',
 'numberofrounds12',
 'outcome12',
 'rating12',
 'referee12',
 'secondBoxer12',
 'secondBoxerLast612',
 'secondBoxerRating12',
 'secondBoxerRecord12',
 'secondBoxerWeight12',
 'titles12',
 'date13',
 'firstBoxerRating13',
 'firstBoxerWeight13',
 'JudgeID13',
 'Links13',
 'location13',
 'metadata13',
 'numberofrounds13',
 'outcome13',
 'rating13',
 'referee13',
 'secondBoxer13',
 'secondBoxerLast613',
 'secondBoxerRating13',
 'secondBoxerRecord13',
 'secondBoxerWeight13',
 'titles13',
 'date14',
 'firstBoxerRating14',
 'firstBoxerWeight14',
 'JudgeID14',
 'Links14',
 'location14',
 'metadata14',
 'numberofrounds14',
 'outcome14',
 'rating14',
 'referee14',
 'secondBoxer14',
 'secondBoxerLast614',
 'secondBoxerRating14',
 'secondBoxerRecord14',
 'secondBoxerWeight14',
 'titles14',
 'date15',
 'firstBoxerRating15',
 'firstBoxerWeight15',
 'JudgeID15',
 'Links15',
 'location15',
 'metadata15',
 'numberofrounds15',
 'outcome15',
 'rating15',
 'referee15',
 'secondBoxer15',
 'secondBoxerLast615',
 'secondBoxerRating15',
 'secondBoxerRecord15',
 'secondBoxerWeight15',
 'titles15',
 'date16',
 'firstBoxerRating16',
 'firstBoxerWeight16',
 'JudgeID16',
 'Links16',
 'location16',
 'metadata16',
 'numberofrounds16',
 'outcome16',
 'rating16',
 'referee16',
 'secondBoxer16',
 'secondBoxerLast616',
 'secondBoxerRating16',
 'secondBoxerRecord16',
 'secondBoxerWeight16',
 'titles16',
 'date17',
 'firstBoxerRating17',
 'firstBoxerWeight17',
 'JudgeID17',
 'Links17',
 'location17',
 'metadata17',
 'numberofrounds17',
 'outcome17',
 'rating17',
 'referee17',
 'secondBoxer17',
 'secondBoxerLast617',
 'secondBoxerRating17',
 'secondBoxerRecord17',
 'secondBoxerWeight17',
 'titles17',
 'date18',
 'firstBoxerRating18',
 'firstBoxerWeight18',
 'JudgeID18',
 'Links18',
 'location18',
 'metadata18',
 'numberofrounds18',
 'outcome18',
 'rating18',
 'referee18',
 'secondBoxer18',
 'secondBoxerLast618',
 'secondBoxerRating18',
 'secondBoxerRecord18',
 'secondBoxerWeight18',
 'titles18',
 'date19',
 'firstBoxerRating19',
 'firstBoxerWeight19',
 'JudgeID19',
 'Links19',
 'location19',
 'metadata19',
 'numberofrounds19',
 'outcome19',
 'rating19',
 'referee19',
 'secondBoxer19',
 'secondBoxerLast619',
 'secondBoxerRating19',
 'secondBoxerRecord19',
 'secondBoxerWeight19',
 'titles19',
 'date20',
 'firstBoxerRating20',
 'firstBoxerWeight20',
 'JudgeID20',
 'Links20',
 'location20',
 'metadata20',
 'numberofrounds20',
 'outcome20',
 'rating20',
 'referee20',
 'secondBoxer20',
 'secondBoxerLast620',
 'secondBoxerRating20',
 'secondBoxerRecord20',
 'secondBoxerWeight20',
 'titles20',
 'date21',
 'firstBoxerRating21',
 'firstBoxerWeight21',
 'JudgeID21',
 'Links21',
 'location21',
 'metadata21',
 'numberofrounds21',
 'outcome21',
 'rating21',
 'referee21',
 'secondBoxer21',
 'secondBoxerLast621',
 'secondBoxerRating21',
 'secondBoxerRecord21',
 'secondBoxerWeight21',
 'titles21',
 'date22',
 'firstBoxerRating22',
 'firstBoxerWeight22',
 'JudgeID22',
 'Links22',
 'location22',
 'metadata22',
 'numberofrounds22',
 'outcome22',
 'rating22',
 'referee22',
 'secondBoxer22',
 'secondBoxerLast622',
 'secondBoxerRating22',
 'secondBoxerRecord22',
 'secondBoxerWeight22',
 'titles22',
 'date23',
 'firstBoxerRating23',
 'firstBoxerWeight23',
 'JudgeID23',
 'Links23',
 'location23',
 'metadata23',
 'numberofrounds23',
 'outcome23',
 'rating23',
 'referee23',
 'secondBoxer23',
 'secondBoxerLast623',
 'secondBoxerRating23',
 'secondBoxerRecord23',
 'secondBoxerWeight23',
 'titles23',
 'date24',
 'firstBoxerRating24',
 'firstBoxerWeight24',
 'JudgeID24',
 'Links24',
 'location24',
 'metadata24',
 'numberofrounds24',
 'outcome24',
 'rating24',
 'referee24',
 'secondBoxer24',
 'secondBoxerLast624',
 'secondBoxerRating24',
 'secondBoxerRecord24',
 'secondBoxerWeight24',
 'titles24',
 'date25',
 'firstBoxerRating25',
 'firstBoxerWeight25',
 'JudgeID25',
 'Links25',
 'location25',
 'metadata25',
 'numberofrounds25',
 'outcome25',
 'rating25',
 'referee25',
 'secondBoxer25',
 'secondBoxerLast625',
 'secondBoxerRating25',
 'secondBoxerRecord25',
 'secondBoxerWeight25',
 'titles25',
 'date26',
 'firstBoxerRating26',
 'firstBoxerWeight26',
 'JudgeID26',
 'Links26',
 'location26',
 'metadata26',
 'numberofrounds26',
 'outcome26',
 'rating26',
 'referee26',
 'secondBoxer26',
 'secondBoxerLast626',
 'secondBoxerRating26',
 'secondBoxerRecord26',
 'secondBoxerWeight26',
 'titles26',
 'date27',
 'firstBoxerRating27',
 'firstBoxerWeight27',
 'JudgeID27',
 'Links27',
 'location27',
 'metadata27',
 'numberofrounds27',
 'outcome27',
 'rating27',
 'referee27',
 'secondBoxer27',
 'secondBoxerLast627',
 'secondBoxerRating27',
 'secondBoxerRecord27',
 'secondBoxerWeight27',
 'titles27',
 'date28',
 'firstBoxerRating28',
 'firstBoxerWeight28',
 'JudgeID28',
 'Links28',
 'location28',
 'metadata28',
 'numberofrounds28',
 'outcome28',
 'rating28',
 'referee28',
 'secondBoxer28',
 'secondBoxerLast628',
 'secondBoxerRating28',
 'secondBoxerRecord28',
 'secondBoxerWeight28',
 'titles28',
 'date29',
 'firstBoxerRating29',
 'firstBoxerWeight29',
 'JudgeID29',
 'Links29',
 'location29',
 'metadata29',
 'numberofrounds29',
 'outcome29',
 'rating29',
 'referee29',
 'secondBoxer29',
 'secondBoxerLast629',
 'secondBoxerRating29',
 'secondBoxerRecord29',
 'secondBoxerWeight29',
 'titles29',
 'date30',
 'firstBoxerRating30',
 'firstBoxerWeight30',
 'JudgeID30',
 'Links30',
 'location30',
 'metadata30',
 'numberofrounds30',
 'outcome30',
 'rating30',
 'referee30',
 'secondBoxer30',
 'secondBoxerLast630',
 'secondBoxerRating30',
 'secondBoxerRecord30',
 'secondBoxerWeight30',
 'titles30',
 'date31',
 'firstBoxerRating31',
 'firstBoxerWeight31',
 'JudgeID31',
 'Links31',
 'location31',
 'metadata31',
 'numberofrounds31',
 'outcome31',
 'rating31',
 'referee31',
 'secondBoxer31',
 'secondBoxerLast631',
 'secondBoxerRating31',
 'secondBoxerRecord31',
 'secondBoxerWeight31',
 'titles31',
 'date32',
 'firstBoxerRating32',
 'firstBoxerWeight32',
 'JudgeID32',
 'Links32',
 'location32',
 'metadata32',
 'numberofrounds32',
 'outcome32',
 'rating32',
 'referee32',
 'secondBoxer32',
 'secondBoxerLast632',
 'secondBoxerRating32',
 'secondBoxerRecord32',
 'secondBoxerWeight32',
 'titles32',
 'date33',
 'firstBoxerRating33',
 'firstBoxerWeight33',
 'JudgeID33',
 'Links33',
 'location33',
 'metadata33',
 'numberofrounds33',
 'outcome33',
 'rating33',
 'referee33',
 'secondBoxer33',
 'secondBoxerLast633',
 'secondBoxerRating33',
 'secondBoxerRecord33',
 'secondBoxerWeight33',
 'titles33',
 'date34',
 'firstBoxerRating34',
 'firstBoxerWeight34',
 'JudgeID34',
 'Links34',
 'location34',
 'metadata34',
 'numberofrounds34',
 'outcome34',
 'rating34',
 'referee34',
 'secondBoxer34',
 'secondBoxerLast634',
 'secondBoxerRating34',
 'secondBoxerRecord34',
 'secondBoxerWeight34',
 'titles34',
 'date35',
 'firstBoxerRating35',
 'firstBoxerWeight35',
 'JudgeID35',
 'Links35',
 'location35',
 'metadata35',
 'numberofrounds35',
 'outcome35',
 'rating35',
 'referee35',
 'secondBoxer35',
 'secondBoxerLast635',
 'secondBoxerRating35',
 'secondBoxerRecord35',
 'secondBoxerWeight35',
 'titles35',
 'date36',
 'firstBoxerRating36',
 'firstBoxerWeight36',
 'JudgeID36',
 'Links36',
 'location36',
 'metadata36',
 'numberofrounds36',
 'outcome36',
 'rating36',
 'referee36',
 'secondBoxer36',
 'secondBoxerLast636',
 'secondBoxerRating36',
 'secondBoxerRecord36',
 'secondBoxerWeight36',
 'titles36',
 'date37',
 'firstBoxerRating37',
 'firstBoxerWeight37',
 'JudgeID37',
 'Links37',
 'location37',
 'metadata37',
 'numberofrounds37',
 'outcome37',
 'rating37',
 'referee37',
 'secondBoxer37',
 'secondBoxerLast637',
 'secondBoxerRating37',
 'secondBoxerRecord37',
 'secondBoxerWeight37',
 'titles37',
 'date38',
 'firstBoxerRating38',
 'firstBoxerWeight38',
 'JudgeID38',
 'Links38',
 'location38',
 'metadata38',
 'numberofrounds38',
 'outcome38',
 'rating38',
 'referee38',
 'secondBoxer38',
 'secondBoxerLast638',
 'secondBoxerRating38',
 'secondBoxerRecord38',
 'secondBoxerWeight38',
 'titles38',
 'date39',
 'firstBoxerRating39',
 'firstBoxerWeight39',
 'JudgeID39',
 'Links39',
 'location39',
 'metadata39',
 'numberofrounds39',
 'outcome39',
 'rating39',
 'referee39',
 'secondBoxer39',
 'secondBoxerLast639',
 'secondBoxerRating39',
 'secondBoxerRecord39',
 'secondBoxerWeight39',
 'titles39',
 'date40',
 'firstBoxerRating40',
 'firstBoxerWeight40',
 'JudgeID40',
 'Links40',
 'location40',
 'metadata40',
 'numberofrounds40',
 'outcome40',
 'rating40',
 'referee40',
 'secondBoxer40',
 'secondBoxerLast640',
 'secondBoxerRating40',
 'secondBoxerRecord40',
 'secondBoxerWeight40',
 'titles40',
 'date41',
 'firstBoxerRating41',
 'firstBoxerWeight41',
 'JudgeID41',
 'Links41',
 'location41',
 'metadata41',
 'numberofrounds41',
 'outcome41',
 'rating41',
 'referee41',
 'secondBoxer41',
 'secondBoxerLast641',
 'secondBoxerRating41',
 'secondBoxerRecord41',
 'secondBoxerWeight41',
 'titles41',
 'date42',
 'firstBoxerRating42',
 'firstBoxerWeight42',
 'JudgeID42',
 'Links42',
 'location42',
 'metadata42',
 'numberofrounds42',
 'outcome42',
 'rating42',
 'referee42',
 'secondBoxer42',
 'secondBoxerLast642',
 'secondBoxerRating42',
 'secondBoxerRecord42',
 'secondBoxerWeight42',
 'titles42',
 'date43',
 'firstBoxerRating43',
 'firstBoxerWeight43',
 'JudgeID43',
 'Links43',
 'location43',
 'metadata43',
 'numberofrounds43',
 'outcome43',
 'rating43',
 'referee43',
 'secondBoxer43',
 'secondBoxerLast643',
 'secondBoxerRating43',
 'secondBoxerRecord43',
 'secondBoxerWeight43',
 'titles43',
 'date44',
 'firstBoxerRating44',
 'firstBoxerWeight44',
 'JudgeID44',
 'Links44',
 'location44',
 'metadata44',
 'numberofrounds44',
 'outcome44',
 'rating44',
 'referee44',
 'secondBoxer44',
 'secondBoxerLast644',
 'secondBoxerRating44',
 'secondBoxerRecord44',
 'secondBoxerWeight44',
 'titles44',
 'date45',
 'firstBoxerRating45',
 'firstBoxerWeight45',
 'JudgeID45',
 'Links45',
 'location45',
 'metadata45',
 'numberofrounds45',
 'outcome45',
 'rating45',
 'referee45',
 'secondBoxer45',
 'secondBoxerLast645',
 'secondBoxerRating45',
 'secondBoxerRecord45',
 'secondBoxerWeight45',
 'titles45',
 'date46',
 'firstBoxerRating46',
 'firstBoxerWeight46',
 'JudgeID46',
 'Links46',
 'location46',
 'metadata46',
 'numberofrounds46',
 'outcome46',
 'rating46',
 'referee46',
 'secondBoxer46',
 'secondBoxerLast646',
 'secondBoxerRating46',
 'secondBoxerRecord46',
 'secondBoxerWeight46',
 'titles46',
 'date47',
 'firstBoxerRating47',
 'firstBoxerWeight47',
 'JudgeID47',
 'Links47',
 'location47',
 'metadata47',
 'numberofrounds47',
 'outcome47',
 'rating47',
 'referee47',
 'secondBoxer47',
 'secondBoxerLast647',
 'secondBoxerRating47',
 'secondBoxerRecord47',
 'secondBoxerWeight47',
 'titles47',
 'date48',
 'firstBoxerRating48',
 'firstBoxerWeight48',
 'JudgeID48',
 'Links48',
 'location48',
 'metadata48',
 'numberofrounds48',
 'outcome48',
 'rating48',
 'referee48',
 'secondBoxer48',
 'secondBoxerLast648',
 'secondBoxerRating48',
 'secondBoxerRecord48',
 'secondBoxerWeight48',
 'titles48',
 'date49',
 'firstBoxerRating49',
 'firstBoxerWeight49',
 'JudgeID49',
 'Links49',
 'location49',
 'metadata49',
 'numberofrounds49',
 'outcome49',
 'rating49',
 'referee49',
 'secondBoxer49',
 'secondBoxerLast649',
 'secondBoxerRating49',
 'secondBoxerRecord49',
 'secondBoxerWeight49',
 'titles49',
 'date50',
 'firstBoxerRating50',
 'firstBoxerWeight50',
 'JudgeID50',
 'Links50',
 'location50',
 'metadata50',
 'numberofrounds50',
 'outcome50',
 'rating50',
 'referee50',
 'secondBoxer50',
 'secondBoxerLast650',
 'secondBoxerRating50',
 'secondBoxerRecord50',
 'secondBoxerWeight50',
 'titles50',
 'date51',
 'firstBoxerRating51',
 'firstBoxerWeight51',
 'JudgeID51',
 'Links51',
 'location51',
 'metadata51',
 'numberofrounds51',
 'outcome51',
 'rating51',
 'referee51',
 'secondBoxer51',
 'secondBoxerLast651',
 'secondBoxerRating51',
 'secondBoxerRecord51',
 'secondBoxerWeight51',
 'titles51',
 'date52',
 'firstBoxerRating52',
 'firstBoxerWeight52',
 'JudgeID52',
 'Links52',
 'location52',
 'metadata52',
 'numberofrounds52',
 'outcome52',
 'rating52',
 'referee52',
 'secondBoxer52',
 'secondBoxerLast652',
 'secondBoxerRating52',
 'secondBoxerRecord52',
 'secondBoxerWeight52',
 'titles52',
 'date53',
 'firstBoxerRating53',
 'firstBoxerWeight53',
 'JudgeID53',
 'Links53',
 'location53',
 'metadata53',
 'numberofrounds53',
 'outcome53',
 'rating53',
 'referee53',
 'secondBoxer53',
 'secondBoxerLast653',
 'secondBoxerRating53',
 'secondBoxerRecord53',
 'secondBoxerWeight53',
 'titles53',
 'date54',
 'firstBoxerRating54',
 'firstBoxerWeight54',
 'JudgeID54',
 'Links54',
 'location54',
 'metadata54',
 'numberofrounds54',
 'outcome54',
 'rating54',
 'referee54',
 'secondBoxer54',
 'secondBoxerLast654',
 'secondBoxerRating54',
 'secondBoxerRecord54',
 'secondBoxerWeight54',
 'titles54',
 'date55',
 'firstBoxerRating55',
 'firstBoxerWeight55',
 'JudgeID55',
 'Links55',
 'location55',
 'metadata55',
 'numberofrounds55',
 'outcome55',
 'rating55',
 'referee55',
 'secondBoxer55',
 'secondBoxerLast655',
 'secondBoxerRating55',
 'secondBoxerRecord55',
 'secondBoxerWeight55',
 'titles55',
 'date56',
 'firstBoxerRating56',
 'firstBoxerWeight56',
 'JudgeID56',
 'Links56',
 'location56',
 'metadata56',
 'numberofrounds56',
 'outcome56',
 'rating56',
 'referee56',
 'secondBoxer56',
 'secondBoxerLast656',
 'secondBoxerRating56',
 'secondBoxerRecord56',
 'secondBoxerWeight56',
 'titles56',
 'date57',
 'firstBoxerRating57',
 'firstBoxerWeight57',
 'JudgeID57',
 'Links57',
 'location57',
 'metadata57',
 'numberofrounds57',
 'outcome57',
 'rating57',
 'referee57',
 'secondBoxer57',
 'secondBoxerLast657',
 'secondBoxerRating57',
 'secondBoxerRecord57',
 'secondBoxerWeight57',
 'titles57',
 'date58',
 'firstBoxerRating58',
 'firstBoxerWeight58',
 'JudgeID58',
 'Links58',
 'location58',
 'metadata58',
 'numberofrounds58',
 'outcome58',
 'rating58',
 'referee58',
 'secondBoxer58',
 'secondBoxerLast658',
 'secondBoxerRating58',
 'secondBoxerRecord58',
 'secondBoxerWeight58',
 'titles58',
 'date59',
 ...]

In [7]:
#iterate through fighters and stances
#iterate through all names in names list
#find fighting stance and match outcome
data
new = pd.read_csv('C:\\Users\\User\\Downloads\\player_profile.csv')
merged_df = pd.merge(data,new[['stance','age','Name']],left_on='name',right_on='Name',how ='left')

In [8]:
merged_df['stance'].fillna('unknown',inplace=True)

In [9]:
second_name = ['secondBoxer'+str(i) for i in range(1,85)]
def letter_only(col):
    return merged_df[col].astype(str).str.replace('"','').astype(str)
for i in second_name:
    merged_df[i] = letter_only(str(i))

In [10]:
limited = merged_df[['name','stance','age','division']]

In [11]:
num = 0 
for i in second_name:
    num +=1
    globals () [i] = pd.merge(merged_df[[i,'outcome'+str(num)]],merged_df[['name','stance']],left_on=i,right_on='name',suffixes=('s'+str(num),'opponent'+str(num)))

In [12]:
fully_merged = pd.concat([limited,secondBoxer1,secondBoxer2,secondBoxer3,secondBoxer4,secondBoxer5,
           secondBoxer6,secondBoxer7,secondBoxer8,secondBoxer9,secondBoxer10,
           secondBoxer11,secondBoxer12,secondBoxer13,secondBoxer14,secondBoxer15,
           secondBoxer16,secondBoxer17,secondBoxer18,secondBoxer19,secondBoxer20,
           secondBoxer21,secondBoxer22,secondBoxer23,secondBoxer24,secondBoxer25,
           secondBoxer26,secondBoxer27,secondBoxer28,secondBoxer29,secondBoxer30,
           secondBoxer31,secondBoxer32,secondBoxer33,secondBoxer34,secondBoxer35,
           secondBoxer36,secondBoxer37,secondBoxer38,secondBoxer39,secondBoxer40,
           secondBoxer41,secondBoxer42,secondBoxer43,secondBoxer44,secondBoxer45,
           secondBoxer46,secondBoxer47,secondBoxer48,secondBoxer49,secondBoxer50,
           secondBoxer51,secondBoxer52,secondBoxer53,secondBoxer54,secondBoxer55,
           secondBoxer56,secondBoxer57,secondBoxer58,secondBoxer59,secondBoxer60,
           secondBoxer61,secondBoxer62,secondBoxer63,secondBoxer64,secondBoxer65,
           secondBoxer66,secondBoxer67,secondBoxer68,secondBoxer69,secondBoxer70,
           secondBoxer71,secondBoxer72,secondBoxer73,secondBoxer74,secondBoxer75,
           secondBoxer76,secondBoxer77,secondBoxer78,secondBoxer79,secondBoxer80,
           secondBoxer81,secondBoxer82,secondBoxer83,secondBoxer84],axis=1)

In [24]:
import numpy as np
select_cols = fully_merged.columns.to_series()
count = select_cols.groupby(level=0).cumcount().add(1).astype(str)
fully_merged.columns = np.where(select_cols == 'stance', 'stance' + count, select_cols)
fully_merged.columns = np.where(select_cols == 'name', 'name' + count, select_cols)

In [ ]:
name_lis = ['name'+str(i) for i in range(2,86)]
fully_merged.drop(name_lis,axis=1,inplace=True)

In [ ]:
fully_merged = pd.concat([limited,secondBoxer1,secondBoxer2,secondBoxer3,secondBoxer4,secondBoxer5,
           secondBoxer6,secondBoxer7,secondBoxer8,secondBoxer9,secondBoxer10,
           secondBoxer11,secondBoxer12,secondBoxer13,secondBoxer14,secondBoxer15,
           secondBoxer16,secondBoxer17,secondBoxer18,secondBoxer19,secondBoxer20,
           secondBoxer21,secondBoxer22,secondBoxer23,secondBoxer24,secondBoxer25,
           secondBoxer26,secondBoxer27,secondBoxer28,secondBoxer29,secondBoxer30,
           secondBoxer31,secondBoxer32,secondBoxer33,secondBoxer34,secondBoxer35,
           secondBoxer36,secondBoxer37,secondBoxer38,secondBoxer39,secondBoxer40,
           secondBoxer41,secondBoxer42,secondBoxer43,secondBoxer44,secondBoxer45,
           secondBoxer46,secondBoxer47,secondBoxer48,secondBoxer49,secondBoxer50,
           secondBoxer51,secondBoxer52,secondBoxer53,secondBoxer54,secondBoxer55,
           secondBoxer56,secondBoxer57,secondBoxer58,secondBoxer59,secondBoxer60,
           secondBoxer61,secondBoxer62,secondBoxer63,secondBoxer64,secondBoxer65,
           secondBoxer66,secondBoxer67,secondBoxer68,secondBoxer69,secondBoxer70,
           secondBoxer71,secondBoxer72,secondBoxer73,secondBoxer74,secondBoxer75,
           secondBoxer76,secondBoxer77,secondBoxer78,secondBoxer79,secondBoxer80,
           secondBoxer81,secondBoxer82,secondBoxer83,secondBoxer84],axis=1)

In [ ]:
fully_merged.reset_index(inplace=True)

In [14]:
fully_merged.head()

,name,stance,age,division,secondBoxer1,outcome1,name,stance,secondBoxer2,outcome2,...,name,stance,secondBoxer83,outcome83,name,stance,secondBoxer84,outcome84,name,stance
0,Roberto Salas,southpaw,30.0,cruiser,Billy Martin,"""win""",Billy Martin,unknown,Leesa Daniels,"""win""",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,James Jackson,unknown,22.0,heavy,Billy Martin,"""win""",Billy Martin,unknown,Leesa Daniels,"""win""",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Alex Love,orthodox,30.0,bantam,Billy Martin,"""win""",Billy Martin,unknown,Coy Lanbert,"""win""",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Juan Centeno,unknown,24.0,fly,Mark Anderson,"""win""",Mark Anderson,unknown,Billy Wagner,"""loss""",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Jordan Weeks,unknown,27.0,super middle,Eddie Sisneros,"""win""",Eddie Sisneros,unknown,Billy Wagner,"""win""",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [444]:
df2 = pd.concat([fully_merged[['name1','stance1','division','secondBoxer1','stance2','outcome1']].rename(columns={'secondBoxer1':'opponent','stance2':'stance.y','outcome1':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer2','stance3','outcome2']].rename(columns={'secondBoxer2':'opponent','stance3':'stance.y','outcome2':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer3','stance4','outcome3']].rename(columns={'secondBoxer3':'opponent','stance4':'stance.y','outcome3':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer4','stance5','outcome4']].rename(columns={'secondBoxer4':'opponent','stance5':'stance.y','outcome4':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer5','stance6','outcome5']].rename(columns={'secondBoxer5':'opponent','stance6':'stance.y','outcome5':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer6','stance7','outcome6']].rename(columns={'secondBoxer6':'opponent','stance7':'stance.y','outcome6':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer7','stance8','outcome7']].rename(columns={'secondBoxer7':'opponent','stance8':'stance.y','outcome7':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer8','stance9','outcome8']].rename(columns={'secondBoxer8':'opponent','stance9':'stance.y','outcome8':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer9','stance10','outcome9']].rename(columns={'secondBoxer9':'opponent','stance10':'stance.y','outcome9':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer10','stance11','outcome10']].rename(columns={'secondBoxer10':'opponent','stance11':'stance.y','outcome10':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer11','stance12','outcome11']].rename(columns={'secondBoxer11':'opponent','stance12':'stance.y','outcome11':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer12','stance13','outcome12']].rename(columns={'secondBoxer12':'opponent','stance13':'stance.y','outcome12':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer13','stance14','outcome13']].rename(columns={'secondBoxer13':'opponent','stance14':'stance.y','outcome13':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer14','stance15','outcome14']].rename(columns={'secondBoxer14':'opponent','stance15':'stance.y','outcome14':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer15','stance16','outcome15']].rename(columns={'secondBoxer15':'opponent','stance16':'stance.y','outcome15':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer16','stance17','outcome16']].rename(columns={'secondBoxer16':'opponent','stance17':'stance.y','outcome16':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer17','stance18','outcome17']].rename(columns={'secondBoxer17':'opponent','stance18':'stance.y','outcome17':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer18','stance19','outcome18']].rename(columns={'secondBoxer18':'opponent','stance19':'stance.y','outcome18':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer19','stance20','outcome19']].rename(columns={'secondBoxer19':'opponent','stance20':'stance.y','outcome19':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer20','stance21','outcome20']].rename(columns={'secondBoxer20':'opponent','stance21':'stance.y','outcome20':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer21','stance22','outcome21']].rename(columns={'secondBoxer21':'opponent','stance22':'stance.y','outcome21':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer22','stance23','outcome22']].rename(columns={'secondBoxer22':'opponent','stance23':'stance.y','outcome22':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer23','stance24','outcome23']].rename(columns={'secondBoxer23':'opponent','stance24':'stance.y','outcome23':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer24','stance25','outcome24']].rename(columns={'secondBoxer24':'opponent','stance25':'stance.y','outcome24':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer25','stance26','outcome25']].rename(columns={'secondBoxer25':'opponent','stance26':'stance.y','outcome25':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer26','stance27','outcome26']].rename(columns={'secondBoxer26':'opponent','stance27':'stance.y','outcome26':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer27','stance28','outcome27']].rename(columns={'secondBoxer27':'opponent','stance28':'stance.y','outcome27':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer28','stance29','outcome28']].rename(columns={'secondBoxer28':'opponent','stance29':'stance.y','outcome28':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer29','stance30','outcome29']].rename(columns={'secondBoxer29':'opponent','stance30':'stance.y','outcome29':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer30','stance31','outcome30']].rename(columns={'secondBoxer30':'opponent','stance31':'stance.y','outcome30':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer31','stance32','outcome31']].rename(columns={'secondBoxer31':'opponent','stance32':'stance.y','outcome31':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer32','stance33','outcome32']].rename(columns={'secondBoxer32':'opponent','stance33':'stance.y','outcome32':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer33','stance34','outcome33']].rename(columns={'secondBoxer33':'opponent','stance34':'stance.y','outcome33':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer34','stance35','outcome34']].rename(columns={'secondBoxer34':'opponent','stance35':'stance.y','outcome34':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer35','stance36','outcome35']].rename(columns={'secondBoxer35':'opponent','stance36':'stance.y','outcome35':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer36','stance37','outcome36']].rename(columns={'secondBoxer36':'opponent','stance37':'stance.y','outcome36':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer37','stance38','outcome37']].rename(columns={'secondBoxer37':'opponent','stance38':'stance.y','outcome37':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer38','stance39','outcome38']].rename(columns={'secondBoxer38':'opponent','stance39':'stance.y','outcome38':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer39','stance40','outcome39']].rename(columns={'secondBoxer39':'opponent','stance40':'stance.y','outcome39':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer40','stance41','outcome40']].rename(columns={'secondBoxer40':'opponent','stance41':'stance.y','outcome40':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer41','stance42','outcome41']].rename(columns={'secondBoxer41':'opponent','stance42':'stance.y','outcome41':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer42','stance43','outcome42']].rename(columns={'secondBoxer42':'opponent','stance43':'stance.y','outcome42':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer43','stance44','outcome43']].rename(columns={'secondBoxer43':'opponent','stance44':'stance.y','outcome43':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer44','stance45','outcome44']].rename(columns={'secondBoxer44':'opponent','stance45':'stance.y','outcome44':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer45','stance46','outcome45']].rename(columns={'secondBoxer45':'opponent','stance46':'stance.y','outcome45':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer46','stance47','outcome46']].rename(columns={'secondBoxer46':'opponent','stance47':'stance.y','outcome46':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer47','stance48','outcome47']].rename(columns={'secondBoxer47':'opponent','stance48':'stance.y','outcome47':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer48','stance49','outcome48']].rename(columns={'secondBoxer48':'opponent','stance49':'stance.y','outcome48':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer49','stance50','outcome49']].rename(columns={'secondBoxer49':'opponent','stance50':'stance.y','outcome49':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer50','stance51','outcome50']].rename(columns={'secondBoxer50':'opponent','stance51':'stance.y','outcome50':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer51','stance52','outcome51']].rename(columns={'secondBoxer51':'opponent','stance52':'stance.y','outcome51':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer52','stance53','outcome52']].rename(columns={'secondBoxer52':'opponent','stance53':'stance.y','outcome52':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer53','stance54','outcome53']].rename(columns={'secondBoxer53':'opponent','stance54':'stance.y','outcome53':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer54','stance55','outcome54']].rename(columns={'secondBoxer54':'opponent','stance55':'stance.y','outcome54':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer55','stance56','outcome55']].rename(columns={'secondBoxer55':'opponent','stance56':'stance.y','outcome55':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer56','stance57','outcome56']].rename(columns={'secondBoxer56':'opponent','stance57':'stance.y','outcome56':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer57','stance58','outcome57']].rename(columns={'secondBoxer57':'opponent','stance58':'stance.y','outcome57':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer58','stance59','outcome58']].rename(columns={'secondBoxer58':'opponent','stance59':'stance.y','outcome58':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer59','stance60','outcome59']].rename(columns={'secondBoxer59':'opponent','stance60':'stance.y','outcome59':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer60','stance61','outcome60']].rename(columns={'secondBoxer60':'opponent','stance61':'stance.y','outcome60':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer61','stance62','outcome61']].rename(columns={'secondBoxer61':'opponent','stance62':'stance.y','outcome61':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer62','stance63','outcome62']].rename(columns={'secondBoxer62':'opponent','stance63':'stance.y','outcome62':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer63','stance64','outcome63']].rename(columns={'secondBoxer63':'opponent','stance64':'stance.y','outcome63':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer64','stance65','outcome64']].rename(columns={'secondBoxer64':'opponent','stance65':'stance.y','outcome64':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer65','stance66','outcome65']].rename(columns={'secondBoxer65':'opponent','stance66':'stance.y','outcome65':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer66','stance67','outcome66']].rename(columns={'secondBoxer66':'opponent','stance67':'stance.y','outcome66':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer67','stance68','outcome67']].rename(columns={'secondBoxer67':'opponent','stance68':'stance.y','outcome67':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer68','stance69','outcome68']].rename(columns={'secondBoxer68':'opponent','stance69':'stance.y','outcome68':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer69','stance70','outcome69']].rename(columns={'secondBoxer69':'opponent','stance70':'stance.y','outcome69':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer70','stance71','outcome70']].rename(columns={'secondBoxer70':'opponent','stance71':'stance.y','outcome70':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer71','stance72','outcome71']].rename(columns={'secondBoxer71':'opponent','stance72':'stance.y','outcome71':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer72','stance73','outcome72']].rename(columns={'secondBoxer72':'opponent','stance73':'stance.y','outcome72':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer73','stance74','outcome73']].rename(columns={'secondBoxer73':'opponent','stance74':'stance.y','outcome73':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer74','stance75','outcome74']].rename(columns={'secondBoxer74':'opponent','stance75':'stance.y','outcome74':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer75','stance76','outcome75']].rename(columns={'secondBoxer75':'opponent','stance76':'stance.y','outcome75':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer76','stance77','outcome76']].rename(columns={'secondBoxer76':'opponent','stance77':'stance.y','outcome76':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer77','stance78','outcome77']].rename(columns={'secondBoxer77':'opponent','stance78':'stance.y','outcome77':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer78','stance79','outcome78']].rename(columns={'secondBoxer78':'opponent','stance79':'stance.y','outcome78':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer79','stance80','outcome79']].rename(columns={'secondBoxer79':'opponent','stance80':'stance.y','outcome79':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer80','stance81','outcome80']].rename(columns={'secondBoxer80':'opponent','stance81':'stance.y','outcome80':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer81','stance82','outcome81']].rename(columns={'secondBoxer81':'opponent','stance82':'stance.y','outcome81':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer82','stance83','outcome82']].rename(columns={'secondBoxer82':'opponent','stance83':'stance.y','outcome82':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer83','stance84','outcome83']].rename(columns={'secondBoxer83':'opponent','stance84':'stance.y','outcome83':'outcome'}),
                 fully_merged[['name1','stance1','division','secondBoxer84','stance85','outcome84']].rename(columns={'secondBoxer84':'opponent','stance85':'stance.y','outcome84':'outcome'})])

In [771]:
df2

         division  total
0          bantam    289
1         cruiser    996
2         feather    723
3             fly    114
4           heavy   1760
5           light   1015
6       light fly     19
7     light heavy    646
8          middle   1220
9         minimum      0
10   super bantam    404
11  super feather    810
12      super fly     96
13    super light   1367
14   super middle   1127
15   super welter   1149
16         welter   1817

In [770]:
df2['outcome'] = df2['outcome'].str.replace('"','')
df2[['outcome','division','age']].fillna('unknown',inplace=True)
# df3 = df2[df2['outcome'].str.contains('win')].groupby(['stance1', 'stance.y'])['outcome'].count().reset_index()

KeyError: "['sex', 'outcome', 'age'] not in index"

In [446]:
df2.to_csv('C:\\Users\\User\\long_formadata.csv')

In [774]:
df5

         division  total
0          bantam    289
1         cruiser    996
2         feather    723
3             fly    114
4           heavy   1760
5           light   1015
6       light fly     19
7     light heavy    646
8          middle   1220
9         minimum      0
10   super bantam    404
11  super feather    810
12      super fly     96
13    super light   1367
14   super middle   1127
15   super welter   1149
16         welter   1817

In [447]:
df3 = df2[df2['outcome'].str.contains('win',na=False)].groupby(['stance1', 'stance.y','division'])['outcome'].count().reset_index()

In [419]:
outcomes_list = ['win','loss','draw','unknown','scheduled','unknown2']
df4 = df2[df2['outcome'].str.contains('|'.join(outcomes_list),na=False)].groupby(['stance1', 'stance.y','division'])['outcome'].count().reset_index()

In [449]:
df5 = df2[['division','outcome']].groupby('division').count().reset_index()
df5.rename(columns={'outcome':'total'},inplace=True)
df3.merge(df5,on='division')

      stance1  stance.y   division  outcome  total
0    orthodox  orthodox     bantam       43    289
1    orthodox  southpaw     bantam       10    289
2    orthodox   unknown     bantam       37    289
3    southpaw  orthodox     bantam        1    289
4    southpaw   unknown     bantam        1    289
..        ...       ...        ...      ...    ...
123   unknown  orthodox     welter      133   1817
124   unknown  southpaw     welter       22   1817
125   unknown   unknown     welter      136   1817
126  orthodox   unknown  light fly        2     19
127   unknown   unknown  light fly        5     19

[128 rows x 5 columns]

In [420]:
df4.rename(columns={'outcome':'total_fights'},inplace=True)

In [421]:
df3['total_fights'] = df4['total_fights']

In [408]:
df3['win_rate'] =df3['outcome']/df3['total_fights'] *100

In [410]:
df3 = df3[df3.stance1 != 'unknown']
df3['total_fights'].max()

439

In [3]:
long_data = pd.read_csv('C:\\Users\\User\\long_formadata.csv')
#count wins by stance
df = long_data[long_data['outcome'].str.contains('win',na=False)].groupby(['stance1', 'stance.y','division'])['outcome'].count().reset_index()
#count total fights by stance
df2 = long_data[['division','outcome']].groupby('division').count().reset_index()
df2.rename(columns={'outcome':'total'},inplace=True)
df = df.merge(df2,on='division')
df['win_rate'] =df['outcome']/df['total'] *100

In [25]:
fully_merged

,name1,stance,age,division,secondBoxer1,outcome1,name2,stance,secondBoxer2,outcome2,...,name83,stance,secondBoxer83,outcome83,name84,stance,secondBoxer84,outcome84,name85,stance
0,Roberto Salas,southpaw,30.0,cruiser,Billy Martin,"""win""",Billy Martin,unknown,Leesa Daniels,"""win""",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,James Jackson,unknown,22.0,heavy,Billy Martin,"""win""",Billy Martin,unknown,Leesa Daniels,"""win""",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Alex Love,orthodox,30.0,bantam,Billy Martin,"""win""",Billy Martin,unknown,Coy Lanbert,"""win""",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Juan Centeno,unknown,24.0,fly,Mark Anderson,"""win""",Mark Anderson,unknown,Billy Wagner,"""loss""",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Jordan Weeks,unknown,27.0,super middle,Eddie Sisneros,"""win""",Eddie Sisneros,unknown,Billy Wagner,"""win""",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3872,Kawelo Alcos,unknown,NaN,light fly,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3873,Logan Yoon,unknown,NaN,welter,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3874,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3875,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3876,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
x = long_data.merge(fully_merged[['name1','age']], on = 'name1')
x = x.reindex(columns=['name1','age','stance1','division','opponent','stance.y','outcome'])
x = x.merge(fully_merged[['name1','age']], left_on= 'opponent',right_on='name1')
# x.merge(data[['name','sex']], left_on='name1',right_on='name')
x = x.merge(data[['name','sex']],left_on='name1_x',right_on='name')
x = x.reindex(columns=['name1_x','age_x','sex','stance1','division','opponent','stance.y','outcome','name1_y','age_y','sex'])
x = x.rename(columns = {'name1_x':'name','age_x':'age',})

In [30]:
x

,name,age,sex,stance1,division,opponent,stance.y,outcome,name1_y,age_y,sex
0,Roberto Salas,30.0,male,southpaw,cruiser,Billy Martin,unknown,win,Billy Martin,29.0,male
1,Roberto Salas,30.0,male,southpaw,cruiser,Leesa Daniels,orthodox,win,Leesa Daniels,32.0,male
2,Roberto Salas,30.0,male,southpaw,cruiser,Thomas Turner,unknown,win,Thomas Turner,NaN,male
3,Roberto Salas,30.0,male,southpaw,cruiser,Fernando Caro,unknown,win,Fernando Caro,NaN,male
4,Roberto Salas,30.0,male,southpaw,cruiser,Fernando Caro,unknown,win,Fernando Caro,NaN,male
...,...,...,...,...,...,...,...,...,...,...,...
1115309,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1115310,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1115311,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1115312,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1115313,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
#adding age range
ranges = [15,20,25,30,35,40,45,50,55,65]
x['age_range'] = pd.cut(x['age'],ranges,labels=['15-20','20-25','25-30','30-35','35-40','40-45','45-50','50-55','55-65'])
x['opp_age_range'] = pd.cut(x['age_y'],ranges,labels=['15-20','20-25','25-30','30-35','35-40','40-45','45-50','50-55','55-65'])

In [36]:
#drop duplicate columns
x = x.loc[:,~x.columns.duplicated()]
x.head()

,name,age,sex,stance1,division,opponent,stance.y,outcome,name1_y,age_y,age_range,opp_age_range
0,Roberto Salas,30.0,male,southpaw,cruiser,Billy Martin,unknown,win,Billy Martin,29.0,25-30,25-30
1,Roberto Salas,30.0,male,southpaw,cruiser,Leesa Daniels,orthodox,win,Leesa Daniels,32.0,25-30,30-35
2,Roberto Salas,30.0,male,southpaw,cruiser,Thomas Turner,unknown,win,Thomas Turner,NaN,25-30,NaN
3,Roberto Salas,30.0,male,southpaw,cruiser,Fernando Caro,unknown,win,Fernando Caro,NaN,25-30,NaN
4,Roberto Salas,30.0,male,southpaw,cruiser,Fernando Caro,unknown,win,Fernando Caro,NaN,25-30,NaN

In [45]:
j = pd.DataFrame()
outcomes = ['win','draw','loss']
outcomeslist = '|'.join(outcomes)
wins = x[x['outcome'].str.contains('win',na=False)].groupby(['age_range', 'opp_age_range','division','sex'])['outcome'].count().reset_index()
loss = x[x['outcome'].str.contains('loss',na=False)].groupby(['age_range', 'opp_age_range','division','sex'])['outcome'].count().reset_index()
draw = x[x['outcome'].str.contains('draw',na=False)].groupby(['age_range', 'opp_age_range','division','sex'])['outcome'].count().reset_index()
other = x[~x['outcome'].str.contains(outcomeslist,na=False)].groupby(['age_range', 'opp_age_range','division','sex'])['outcome'].count().reset_index()
j[['age_range','opp_age_range','division','sex','wins']] = wins[['age_range','opp_age_range','division','sex','outcome']]
j = j.merge(loss, on=['age_range','opp_age_range','division','sex']).rename(columns={'outcome':'loss'}).merge(draw, on=['age_range','opp_age_range','division','sex']).rename(columns={'outcome':'draw'}).merge(other, on=['age_range','opp_age_range','division','sex']).rename(columns={'outcome':'other'})

In [46]:
j

    age_range opp_age_range division     sex  wins  loss  outcome
0       15-20         15-20   middle    male     1     1        1
1       15-20         20-25      fly    male     2     2        3
2       15-20         20-25   middle    male     7     8        1
3       15-20         20-25   welter    male    10    15        1
4       15-20         25-30  cruiser    male     6     7        2
..        ...           ...      ...     ...   ...   ...      ...
208     45-50         20-25  cruiser    male     4     3        1
209     45-50         20-25   middle    male     3     3        1
210     45-50         25-30  cruiser    male     2     1        1
211     45-50         25-30    heavy  female     1     2        1
212     45-50         25-30    heavy    male     3     6        2

[213 rows x 7 columns]

In [463]:
data = pd.read_csv('C:\\Users\\User\\Documents\\visuals.csv')
data['division'] = data['division'].fillna('unknown')
data['bouts_fought'] = data['w'].astype('float')+data['l'].astype('float')+data['d'].astype('float')

In [464]:
list(data)

['Unnamed: 0',
 'miles',
 'location',
 'name',
 'sex',
 'w',
 'l',
 'd',
 'division',
 'from',
 'to',
 'players_links',
 'global_id',
 'date1',
 'firstBoxerRating1',
 'firstBoxerWeight1',
 'JudgeID1',
 'Links1',
 'location1',
 'metadata1',
 'numberofrounds1',
 'outcome1',
 'rating1',
 'referee1',
 'secondBoxer1',
 'secondBoxerLast61',
 'secondBoxerRating1',
 'secondBoxerRecord1',
 'secondBoxerWeight1',
 'titles1',
 'date2',
 'firstBoxerRating2',
 'firstBoxerWeight2',
 'JudgeID2',
 'Links2',
 'location2',
 'metadata2',
 'numberofrounds2',
 'outcome2',
 'rating2',
 'referee2',
 'secondBoxer2',
 'secondBoxerLast62',
 'secondBoxerRating2',
 'secondBoxerRecord2',
 'secondBoxerWeight2',
 'titles2',
 'date3',
 'firstBoxerRating3',
 'firstBoxerWeight3',
 'JudgeID3',
 'Links3',
 'location3',
 'metadata3',
 'numberofrounds3',
 'outcome3',
 'rating3',
 'referee3',
 'secondBoxer3',
 'secondBoxerLast63',
 'secondBoxerRating3',
 'secondBoxerRecord3',
 'secondBoxerWeight3',
 'titles3',
 'date4',
 'firstBoxerRating4',
 'firstBoxerWeight4',
 'JudgeID4',
 'Links4',
 'location4',
 'metadata4',
 'numberofrounds4',
 'outcome4',
 'rating4',
 'referee4',
 'secondBoxer4',
 'secondBoxerLast64',
 'secondBoxerRating4',
 'secondBoxerRecord4',
 'secondBoxerWeight4',
 'titles4',
 'date5',
 'firstBoxerRating5',
 'firstBoxerWeight5',
 'JudgeID5',
 'Links5',
 'location5',
 'metadata5',
 'numberofrounds5',
 'outcome5',
 'rating5',
 'referee5',
 'secondBoxer5',
 'secondBoxerLast65',
 'secondBoxerRating5',
 'secondBoxerRecord5',
 'secondBoxerWeight5',
 'titles5',
 'date6',
 'firstBoxerRating6',
 'firstBoxerWeight6',
 'JudgeID6',
 'Links6',
 'location6',
 'metadata6',
 'numberofrounds6',
 'outcome6',
 'rating6',
 'referee6',
 'secondBoxer6',
 'secondBoxerLast66',
 'secondBoxerRating6',
 'secondBoxerRecord6',
 'secondBoxerWeight6',
 'titles6',
 'date7',
 'firstBoxerRating7',
 'firstBoxerWeight7',
 'JudgeID7',
 'Links7',
 'location7',
 'metadata7',
 'numberofrounds7',
 'outcome7',
 'rating7',
 'referee7',
 'secondBoxer7',
 'secondBoxerLast67',
 'secondBoxerRating7',
 'secondBoxerRecord7',
 'secondBoxerWeight7',
 'titles7',
 'date8',
 'firstBoxerRating8',
 'firstBoxerWeight8',
 'JudgeID8',
 'Links8',
 'location8',
 'metadata8',
 'numberofrounds8',
 'outcome8',
 'rating8',
 'referee8',
 'secondBoxer8',
 'secondBoxerLast68',
 'secondBoxerRating8',
 'secondBoxerRecord8',
 'secondBoxerWeight8',
 'titles8',
 'date9',
 'firstBoxerRating9',
 'firstBoxerWeight9',
 'JudgeID9',
 'Links9',
 'location9',
 'metadata9',
 'numberofrounds9',
 'outcome9',
 'rating9',
 'referee9',
 'secondBoxer9',
 'secondBoxerLast69',
 'secondBoxerRating9',
 'secondBoxerRecord9',
 'secondBoxerWeight9',
 'titles9',
 'date10',
 'firstBoxerRating10',
 'firstBoxerWeight10',
 'JudgeID10',
 'Links10',
 'location10',
 'metadata10',
 'numberofrounds10',
 'outcome10',
 'rating10',
 'referee10',
 'secondBoxer10',
 'secondBoxerLast610',
 'secondBoxerRating10',
 'secondBoxerRecord10',
 'secondBoxerWeight10',
 'titles10',
 'date11',
 'firstBoxerRating11',
 'firstBoxerWeight11',
 'JudgeID11',
 'Links11',
 'location11',
 'metadata11',
 'numberofrounds11',
 'outcome11',
 'rating11',
 'referee11',
 'secondBoxer11',
 'secondBoxerLast611',
 'secondBoxerRating11',
 'secondBoxerRecord11',
 'secondBoxerWeight11',
 'titles11',
 'date12',
 'firstBoxerRating12',
 'firstBoxerWeight12',
 'JudgeID12',
 'Links12',
 'location12',
 'metadata12',
 'numberofrounds12',
 'outcome12',
 'rating12',
 'referee12',
 'secondBoxer12',
 'secondBoxerLast612',
 'secondBoxerRating12',
 'secondBoxerRecord12',
 'secondBoxerWeight12',
 'titles12',
 'date13',
 'firstBoxerRating13',
 'firstBoxerWeight13',
 'JudgeID13',
 'Links13',
 'location13',
 'metadata13',
 'numberofrounds13',
 'outcome13',
 'rating13',
 'referee13',
 'secondBoxer13',
 'secondBoxerLast613',
 'secondBoxerRating13',
 'secondBoxerRecord13',
 'secondBoxerWeight13',
 'titles13',
 'date14',
 'firstBoxerRating14',
 'firstBoxerWeight14',
 'JudgeID14',
 'Links14',
 'location14',
 'metadata14',
 'numberofrounds14',
 'outcome14',
 'rating14',
 'referee14',
 'secondBoxer14',
 'secondBoxerLast614',
 'secondBoxerRating14',
 'secondBoxerRecord14',
 'secondBoxerWeight14',
 'titles14',
 'date15',
 'firstBoxerRating15',
 'firstBoxerWeight15',
 'JudgeID15',
 'Links15',
 'location15',
 'metadata15',
 'numberofrounds15',
 'outcome15',
 'rating15',
 'referee15',
 'secondBoxer15',
 'secondBoxerLast615',
 'secondBoxerRating15',
 'secondBoxerRecord15',
 'secondBoxerWeight15',
 'titles15',
 'date16',
 'firstBoxerRating16',
 'firstBoxerWeight16',
 'JudgeID16',
 'Links16',
 'location16',
 'metadata16',
 'numberofrounds16',
 'outcome16',
 'rating16',
 'referee16',
 'secondBoxer16',
 'secondBoxerLast616',
 'secondBoxerRating16',
 'secondBoxerRecord16',
 'secondBoxerWeight16',
 'titles16',
 'date17',
 'firstBoxerRating17',
 'firstBoxerWeight17',
 'JudgeID17',
 'Links17',
 'location17',
 'metadata17',
 'numberofrounds17',
 'outcome17',
 'rating17',
 'referee17',
 'secondBoxer17',
 'secondBoxerLast617',
 'secondBoxerRating17',
 'secondBoxerRecord17',
 'secondBoxerWeight17',
 'titles17',
 'date18',
 'firstBoxerRating18',
 'firstBoxerWeight18',
 'JudgeID18',
 'Links18',
 'location18',
 'metadata18',
 'numberofrounds18',
 'outcome18',
 'rating18',
 'referee18',
 'secondBoxer18',
 'secondBoxerLast618',
 'secondBoxerRating18',
 'secondBoxerRecord18',
 'secondBoxerWeight18',
 'titles18',
 'date19',
 'firstBoxerRating19',
 'firstBoxerWeight19',
 'JudgeID19',
 'Links19',
 'location19',
 'metadata19',
 'numberofrounds19',
 'outcome19',
 'rating19',
 'referee19',
 'secondBoxer19',
 'secondBoxerLast619',
 'secondBoxerRating19',
 'secondBoxerRecord19',
 'secondBoxerWeight19',
 'titles19',
 'date20',
 'firstBoxerRating20',
 'firstBoxerWeight20',
 'JudgeID20',
 'Links20',
 'location20',
 'metadata20',
 'numberofrounds20',
 'outcome20',
 'rating20',
 'referee20',
 'secondBoxer20',
 'secondBoxerLast620',
 'secondBoxerRating20',
 'secondBoxerRecord20',
 'secondBoxerWeight20',
 'titles20',
 'date21',
 'firstBoxerRating21',
 'firstBoxerWeight21',
 'JudgeID21',
 'Links21',
 'location21',
 'metadata21',
 'numberofrounds21',
 'outcome21',
 'rating21',
 'referee21',
 'secondBoxer21',
 'secondBoxerLast621',
 'secondBoxerRating21',
 'secondBoxerRecord21',
 'secondBoxerWeight21',
 'titles21',
 'date22',
 'firstBoxerRating22',
 'firstBoxerWeight22',
 'JudgeID22',
 'Links22',
 'location22',
 'metadata22',
 'numberofrounds22',
 'outcome22',
 'rating22',
 'referee22',
 'secondBoxer22',
 'secondBoxerLast622',
 'secondBoxerRating22',
 'secondBoxerRecord22',
 'secondBoxerWeight22',
 'titles22',
 'date23',
 'firstBoxerRating23',
 'firstBoxerWeight23',
 'JudgeID23',
 'Links23',
 'location23',
 'metadata23',
 'numberofrounds23',
 'outcome23',
 'rating23',
 'referee23',
 'secondBoxer23',
 'secondBoxerLast623',
 'secondBoxerRating23',
 'secondBoxerRecord23',
 'secondBoxerWeight23',
 'titles23',
 'date24',
 'firstBoxerRating24',
 'firstBoxerWeight24',
 'JudgeID24',
 'Links24',
 'location24',
 'metadata24',
 'numberofrounds24',
 'outcome24',
 'rating24',
 'referee24',
 'secondBoxer24',
 'secondBoxerLast624',
 'secondBoxerRating24',
 'secondBoxerRecord24',
 'secondBoxerWeight24',
 'titles24',
 'date25',
 'firstBoxerRating25',
 'firstBoxerWeight25',
 'JudgeID25',
 'Links25',
 'location25',
 'metadata25',
 'numberofrounds25',
 'outcome25',
 'rating25',
 'referee25',
 'secondBoxer25',
 'secondBoxerLast625',
 'secondBoxerRating25',
 'secondBoxerRecord25',
 'secondBoxerWeight25',
 'titles25',
 'date26',
 'firstBoxerRating26',
 'firstBoxerWeight26',
 'JudgeID26',
 'Links26',
 'location26',
 'metadata26',
 'numberofrounds26',
 'outcome26',
 'rating26',
 'referee26',
 'secondBoxer26',
 'secondBoxerLast626',
 'secondBoxerRating26',
 'secondBoxerRecord26',
 'secondBoxerWeight26',
 'titles26',
 'date27',
 'firstBoxerRating27',
 'firstBoxerWeight27',
 'JudgeID27',
 'Links27',
 'location27',
 'metadata27',
 'numberofrounds27',
 'outcome27',
 'rating27',
 'referee27',
 'secondBoxer27',
 'secondBoxerLast627',
 'secondBoxerRating27',
 'secondBoxerRecord27',
 'secondBoxerWeight27',
 'titles27',
 'date28',
 'firstBoxerRating28',
 'firstBoxerWeight28',
 'JudgeID28',
 'Links28',
 'location28',
 'metadata28',
 'numberofrounds28',
 'outcome28',
 'rating28',
 'referee28',
 'secondBoxer28',
 'secondBoxerLast628',
 'secondBoxerRating28',
 'secondBoxerRecord28',
 'secondBoxerWeight28',
 'titles28',
 'date29',
 'firstBoxerRating29',
 'firstBoxerWeight29',
 'JudgeID29',
 'Links29',
 'location29',
 'metadata29',
 'numberofrounds29',
 'outcome29',
 'rating29',
 'referee29',
 'secondBoxer29',
 'secondBoxerLast629',
 'secondBoxerRating29',
 'secondBoxerRecord29',
 'secondBoxerWeight29',
 'titles29',
 'date30',
 'firstBoxerRating30',
 'firstBoxerWeight30',
 'JudgeID30',
 'Links30',
 'location30',
 'metadata30',
 'numberofrounds30',
 'outcome30',
 'rating30',
 'referee30',
 'secondBoxer30',
 'secondBoxerLast630',
 'secondBoxerRating30',
 'secondBoxerRecord30',
 'secondBoxerWeight30',
 'titles30',
 'date31',
 'firstBoxerRating31',
 'firstBoxerWeight31',
 'JudgeID31',
 'Links31',
 'location31',
 'metadata31',
 'numberofrounds31',
 'outcome31',
 'rating31',
 'referee31',
 'secondBoxer31',
 'secondBoxerLast631',
 'secondBoxerRating31',
 'secondBoxerRecord31',
 'secondBoxerWeight31',
 'titles31',
 'date32',
 'firstBoxerRating32',
 'firstBoxerWeight32',
 'JudgeID32',
 'Links32',
 'location32',
 'metadata32',
 'numberofrounds32',
 'outcome32',
 'rating32',
 'referee32',
 'secondBoxer32',
 'secondBoxerLast632',
 'secondBoxerRating32',
 'secondBoxerRecord32',
 'secondBoxerWeight32',
 'titles32',
 'date33',
 'firstBoxerRating33',
 'firstBoxerWeight33',
 'JudgeID33',
 'Links33',
 'location33',
 'metadata33',
 'numberofrounds33',
 'outcome33',
 'rating33',
 'referee33',
 'secondBoxer33',
 'secondBoxerLast633',
 'secondBoxerRating33',
 'secondBoxerRecord33',
 'secondBoxerWeight33',
 'titles33',
 'date34',
 'firstBoxerRating34',
 'firstBoxerWeight34',
 'JudgeID34',
 'Links34',
 'location34',
 'metadata34',
 'numberofrounds34',
 'outcome34',
 'rating34',
 'referee34',
 'secondBoxer34',
 'secondBoxerLast634',
 'secondBoxerRating34',
 'secondBoxerRecord34',
 'secondBoxerWeight34',
 'titles34',
 'date35',
 'firstBoxerRating35',
 'firstBoxerWeight35',
 'JudgeID35',
 'Links35',
 'location35',
 'metadata35',
 'numberofrounds35',
 'outcome35',
 'rating35',
 'referee35',
 'secondBoxer35',
 'secondBoxerLast635',
 'secondBoxerRating35',
 'secondBoxerRecord35',
 'secondBoxerWeight35',
 'titles35',
 'date36',
 'firstBoxerRating36',
 'firstBoxerWeight36',
 'JudgeID36',
 'Links36',
 'location36',
 'metadata36',
 'numberofrounds36',
 'outcome36',
 'rating36',
 'referee36',
 'secondBoxer36',
 'secondBoxerLast636',
 'secondBoxerRating36',
 'secondBoxerRecord36',
 'secondBoxerWeight36',
 'titles36',
 'date37',
 'firstBoxerRating37',
 'firstBoxerWeight37',
 'JudgeID37',
 'Links37',
 'location37',
 'metadata37',
 'numberofrounds37',
 'outcome37',
 'rating37',
 'referee37',
 'secondBoxer37',
 'secondBoxerLast637',
 'secondBoxerRating37',
 'secondBoxerRecord37',
 'secondBoxerWeight37',
 'titles37',
 'date38',
 'firstBoxerRating38',
 'firstBoxerWeight38',
 'JudgeID38',
 'Links38',
 'location38',
 'metadata38',
 'numberofrounds38',
 'outcome38',
 'rating38',
 'referee38',
 'secondBoxer38',
 'secondBoxerLast638',
 'secondBoxerRating38',
 'secondBoxerRecord38',
 'secondBoxerWeight38',
 'titles38',
 'date39',
 'firstBoxerRating39',
 'firstBoxerWeight39',
 'JudgeID39',
 'Links39',
 'location39',
 'metadata39',
 'numberofrounds39',
 'outcome39',
 'rating39',
 'referee39',
 'secondBoxer39',
 'secondBoxerLast639',
 'secondBoxerRating39',
 'secondBoxerRecord39',
 'secondBoxerWeight39',
 'titles39',
 'date40',
 'firstBoxerRating40',
 'firstBoxerWeight40',
 'JudgeID40',
 'Links40',
 'location40',
 'metadata40',
 'numberofrounds40',
 'outcome40',
 'rating40',
 'referee40',
 'secondBoxer40',
 'secondBoxerLast640',
 'secondBoxerRating40',
 'secondBoxerRecord40',
 'secondBoxerWeight40',
 'titles40',
 'date41',
 'firstBoxerRating41',
 'firstBoxerWeight41',
 'JudgeID41',
 'Links41',
 'location41',
 'metadata41',
 'numberofrounds41',
 'outcome41',
 'rating41',
 'referee41',
 'secondBoxer41',
 'secondBoxerLast641',
 'secondBoxerRating41',
 'secondBoxerRecord41',
 'secondBoxerWeight41',
 'titles41',
 'date42',
 'firstBoxerRating42',
 'firstBoxerWeight42',
 'JudgeID42',
 'Links42',
 'location42',
 'metadata42',
 'numberofrounds42',
 'outcome42',
 'rating42',
 'referee42',
 'secondBoxer42',
 'secondBoxerLast642',
 'secondBoxerRating42',
 'secondBoxerRecord42',
 'secondBoxerWeight42',
 'titles42',
 'date43',
 'firstBoxerRating43',
 'firstBoxerWeight43',
 'JudgeID43',
 'Links43',
 'location43',
 'metadata43',
 'numberofrounds43',
 'outcome43',
 'rating43',
 'referee43',
 'secondBoxer43',
 'secondBoxerLast643',
 'secondBoxerRating43',
 'secondBoxerRecord43',
 'secondBoxerWeight43',
 'titles43',
 'date44',
 'firstBoxerRating44',
 'firstBoxerWeight44',
 'JudgeID44',
 'Links44',
 'location44',
 'metadata44',
 'numberofrounds44',
 'outcome44',
 'rating44',
 'referee44',
 'secondBoxer44',
 'secondBoxerLast644',
 'secondBoxerRating44',
 'secondBoxerRecord44',
 'secondBoxerWeight44',
 'titles44',
 'date45',
 'firstBoxerRating45',
 'firstBoxerWeight45',
 'JudgeID45',
 'Links45',
 'location45',
 'metadata45',
 'numberofrounds45',
 'outcome45',
 'rating45',
 'referee45',
 'secondBoxer45',
 'secondBoxerLast645',
 'secondBoxerRating45',
 'secondBoxerRecord45',
 'secondBoxerWeight45',
 'titles45',
 'date46',
 'firstBoxerRating46',
 'firstBoxerWeight46',
 'JudgeID46',
 'Links46',
 'location46',
 'metadata46',
 'numberofrounds46',
 'outcome46',
 'rating46',
 'referee46',
 'secondBoxer46',
 'secondBoxerLast646',
 'secondBoxerRating46',
 'secondBoxerRecord46',
 'secondBoxerWeight46',
 'titles46',
 'date47',
 'firstBoxerRating47',
 'firstBoxerWeight47',
 'JudgeID47',
 'Links47',
 'location47',
 'metadata47',
 'numberofrounds47',
 'outcome47',
 'rating47',
 'referee47',
 'secondBoxer47',
 'secondBoxerLast647',
 'secondBoxerRating47',
 'secondBoxerRecord47',
 'secondBoxerWeight47',
 'titles47',
 'date48',
 'firstBoxerRating48',
 'firstBoxerWeight48',
 'JudgeID48',
 'Links48',
 'location48',
 'metadata48',
 'numberofrounds48',
 'outcome48',
 'rating48',
 'referee48',
 'secondBoxer48',
 'secondBoxerLast648',
 'secondBoxerRating48',
 'secondBoxerRecord48',
 'secondBoxerWeight48',
 'titles48',
 'date49',
 'firstBoxerRating49',
 'firstBoxerWeight49',
 'JudgeID49',
 'Links49',
 'location49',
 'metadata49',
 'numberofrounds49',
 'outcome49',
 'rating49',
 'referee49',
 'secondBoxer49',
 'secondBoxerLast649',
 'secondBoxerRating49',
 'secondBoxerRecord49',
 'secondBoxerWeight49',
 'titles49',
 'date50',
 'firstBoxerRating50',
 'firstBoxerWeight50',
 'JudgeID50',
 'Links50',
 'location50',
 'metadata50',
 'numberofrounds50',
 'outcome50',
 'rating50',
 'referee50',
 'secondBoxer50',
 'secondBoxerLast650',
 'secondBoxerRating50',
 'secondBoxerRecord50',
 'secondBoxerWeight50',
 'titles50',
 'date51',
 'firstBoxerRating51',
 'firstBoxerWeight51',
 'JudgeID51',
 'Links51',
 'location51',
 'metadata51',
 'numberofrounds51',
 'outcome51',
 'rating51',
 'referee51',
 'secondBoxer51',
 'secondBoxerLast651',
 'secondBoxerRating51',
 'secondBoxerRecord51',
 'secondBoxerWeight51',
 'titles51',
 'date52',
 'firstBoxerRating52',
 'firstBoxerWeight52',
 'JudgeID52',
 'Links52',
 'location52',
 'metadata52',
 'numberofrounds52',
 'outcome52',
 'rating52',
 'referee52',
 'secondBoxer52',
 'secondBoxerLast652',
 'secondBoxerRating52',
 'secondBoxerRecord52',
 'secondBoxerWeight52',
 'titles52',
 'date53',
 'firstBoxerRating53',
 'firstBoxerWeight53',
 'JudgeID53',
 'Links53',
 'location53',
 'metadata53',
 'numberofrounds53',
 'outcome53',
 'rating53',
 'referee53',
 'secondBoxer53',
 'secondBoxerLast653',
 'secondBoxerRating53',
 'secondBoxerRecord53',
 'secondBoxerWeight53',
 'titles53',
 'date54',
 'firstBoxerRating54',
 'firstBoxerWeight54',
 'JudgeID54',
 'Links54',
 'location54',
 'metadata54',
 'numberofrounds54',
 'outcome54',
 'rating54',
 'referee54',
 'secondBoxer54',
 'secondBoxerLast654',
 'secondBoxerRating54',
 'secondBoxerRecord54',
 'secondBoxerWeight54',
 'titles54',
 'date55',
 'firstBoxerRating55',
 'firstBoxerWeight55',
 'JudgeID55',
 'Links55',
 'location55',
 'metadata55',
 'numberofrounds55',
 'outcome55',
 'rating55',
 'referee55',
 'secondBoxer55',
 'secondBoxerLast655',
 'secondBoxerRating55',
 'secondBoxerRecord55',
 'secondBoxerWeight55',
 'titles55',
 'date56',
 'firstBoxerRating56',
 'firstBoxerWeight56',
 'JudgeID56',
 'Links56',
 'location56',
 'metadata56',
 'numberofrounds56',
 'outcome56',
 'rating56',
 'referee56',
 'secondBoxer56',
 'secondBoxerLast656',
 'secondBoxerRating56',
 'secondBoxerRecord56',
 'secondBoxerWeight56',
 'titles56',
 'date57',
 'firstBoxerRating57',
 'firstBoxerWeight57',
 'JudgeID57',
 'Links57',
 'location57',
 'metadata57',
 'numberofrounds57',
 'outcome57',
 'rating57',
 'referee57',
 'secondBoxer57',
 'secondBoxerLast657',
 'secondBoxerRating57',
 'secondBoxerRecord57',
 'secondBoxerWeight57',
 'titles57',
 'date58',
 'firstBoxerRating58',
 'firstBoxerWeight58',
 'JudgeID58',
 'Links58',
 'location58',
 'metadata58',
 'numberofrounds58',
 'outcome58',
 'rating58',
 'referee58',
 'secondBoxer58',
 'secondBoxerLast658',
 'secondBoxerRating58',
 'secondBoxerRecord58',
 'secondBoxerWeight58',
 'titles58',
 'date59',
 ...]

In [461]:
data[['name','division','sex','w','d','l','bouts_fought']]

,name,division,sex,bouts_fought,w,l,d,location,from
0,Roberto Salas,cruiser,male,5.0,5.0,0.0,0.0,USA,2016.0
1,James Jackson,heavy,male,5.0,4.0,0.0,1.0,USA,2017.0
2,Alex Love,bantam,female,3.0,3.0,0.0,0.0,USA,2018.0
3,Juan Centeno,fly,male,8.0,4.0,3.0,1.0,USA,2016.0
4,Jordan Weeks,super middle,male,2.0,2.0,0.0,0.0,USA,2019.0
...,...,...,...,...,...,...,...,...,...
3840,Kawelo Alcos,light fly,male,4.0,2.0,0.0,2.0,"USA, Hawaii, Molokai",2017.0
3841,Logan Yoon,welter,male,16.0,16.0,0.0,0.0,"USA, Hawaii, Honolulu",2016.0
3842,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3843,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3844,NaN,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [466]:
data['w']/data['bouts_fought']

0       1.0
1       0.8
2       1.0
3       0.5
4       1.0
       ...
3840    0.5
3841    1.0
3842    NaN
3843    NaN
3844    NaN
Length: 3845, dtype: float64

In [472]:
wil = data[data['name']=='Deontay Wilder']

In [473]:
wil['']

['Unnamed: 0',
 'miles',
 'location',
 'name',
 'sex',
 'w',
 'l',
 'd',
 'division',
 'from',
 'to',
 'players_links',
 'global_id',
 'date1',
 'firstBoxerRating1',
 'firstBoxerWeight1',
 'JudgeID1',
 'Links1',
 'location1',
 'metadata1',
 'numberofrounds1',
 'outcome1',
 'rating1',
 'referee1',
 'secondBoxer1',
 'secondBoxerLast61',
 'secondBoxerRating1',
 'secondBoxerRecord1',
 'secondBoxerWeight1',
 'titles1',
 'date2',
 'firstBoxerRating2',
 'firstBoxerWeight2',
 'JudgeID2',
 'Links2',
 'location2',
 'metadata2',
 'numberofrounds2',
 'outcome2',
 'rating2',
 'referee2',
 'secondBoxer2',
 'secondBoxerLast62',
 'secondBoxerRating2',
 'secondBoxerRecord2',
 'secondBoxerWeight2',
 'titles2',
 'date3',
 'firstBoxerRating3',
 'firstBoxerWeight3',
 'JudgeID3',
 'Links3',
 'location3',
 'metadata3',
 'numberofrounds3',
 'outcome3',
 'rating3',
 'referee3',
 'secondBoxer3',
 'secondBoxerLast63',
 'secondBoxerRating3',
 'secondBoxerRecord3',
 'secondBoxerWeight3',
 'titles3',
 'date4',
 'firstBoxerRating4',
 'firstBoxerWeight4',
 'JudgeID4',
 'Links4',
 'location4',
 'metadata4',
 'numberofrounds4',
 'outcome4',
 'rating4',
 'referee4',
 'secondBoxer4',
 'secondBoxerLast64',
 'secondBoxerRating4',
 'secondBoxerRecord4',
 'secondBoxerWeight4',
 'titles4',
 'date5',
 'firstBoxerRating5',
 'firstBoxerWeight5',
 'JudgeID5',
 'Links5',
 'location5',
 'metadata5',
 'numberofrounds5',
 'outcome5',
 'rating5',
 'referee5',
 'secondBoxer5',
 'secondBoxerLast65',
 'secondBoxerRating5',
 'secondBoxerRecord5',
 'secondBoxerWeight5',
 'titles5',
 'date6',
 'firstBoxerRating6',
 'firstBoxerWeight6',
 'JudgeID6',
 'Links6',
 'location6',
 'metadata6',
 'numberofrounds6',
 'outcome6',
 'rating6',
 'referee6',
 'secondBoxer6',
 'secondBoxerLast66',
 'secondBoxerRating6',
 'secondBoxerRecord6',
 'secondBoxerWeight6',
 'titles6',
 'date7',
 'firstBoxerRating7',
 'firstBoxerWeight7',
 'JudgeID7',
 'Links7',
 'location7',
 'metadata7',
 'numberofrounds7',
 'outcome7',
 'rating7',
 'referee7',
 'secondBoxer7',
 'secondBoxerLast67',
 'secondBoxerRating7',
 'secondBoxerRecord7',
 'secondBoxerWeight7',
 'titles7',
 'date8',
 'firstBoxerRating8',
 'firstBoxerWeight8',
 'JudgeID8',
 'Links8',
 'location8',
 'metadata8',
 'numberofrounds8',
 'outcome8',
 'rating8',
 'referee8',
 'secondBoxer8',
 'secondBoxerLast68',
 'secondBoxerRating8',
 'secondBoxerRecord8',
 'secondBoxerWeight8',
 'titles8',
 'date9',
 'firstBoxerRating9',
 'firstBoxerWeight9',
 'JudgeID9',
 'Links9',
 'location9',
 'metadata9',
 'numberofrounds9',
 'outcome9',
 'rating9',
 'referee9',
 'secondBoxer9',
 'secondBoxerLast69',
 'secondBoxerRating9',
 'secondBoxerRecord9',
 'secondBoxerWeight9',
 'titles9',
 'date10',
 'firstBoxerRating10',
 'firstBoxerWeight10',
 'JudgeID10',
 'Links10',
 'location10',
 'metadata10',
 'numberofrounds10',
 'outcome10',
 'rating10',
 'referee10',
 'secondBoxer10',
 'secondBoxerLast610',
 'secondBoxerRating10',
 'secondBoxerRecord10',
 'secondBoxerWeight10',
 'titles10',
 'date11',
 'firstBoxerRating11',
 'firstBoxerWeight11',
 'JudgeID11',
 'Links11',
 'location11',
 'metadata11',
 'numberofrounds11',
 'outcome11',
 'rating11',
 'referee11',
 'secondBoxer11',
 'secondBoxerLast611',
 'secondBoxerRating11',
 'secondBoxerRecord11',
 'secondBoxerWeight11',
 'titles11',
 'date12',
 'firstBoxerRating12',
 'firstBoxerWeight12',
 'JudgeID12',
 'Links12',
 'location12',
 'metadata12',
 'numberofrounds12',
 'outcome12',
 'rating12',
 'referee12',
 'secondBoxer12',
 'secondBoxerLast612',
 'secondBoxerRating12',
 'secondBoxerRecord12',
 'secondBoxerWeight12',
 'titles12',
 'date13',
 'firstBoxerRating13',
 'firstBoxerWeight13',
 'JudgeID13',
 'Links13',
 'location13',
 'metadata13',
 'numberofrounds13',
 'outcome13',
 'rating13',
 'referee13',
 'secondBoxer13',
 'secondBoxerLast613',
 'secondBoxerRating13',
 'secondBoxerRecord13',
 'secondBoxerWeight13',
 'titles13',
 'date14',
 'firstBoxerRating14',
 'firstBoxerWeight14',
 'JudgeID14',
 'Links14',
 'location14',
 'metadata14',
 'numberofrounds14',
 'outcome14',
 'rating14',
 'referee14',
 'secondBoxer14',
 'secondBoxerLast614',
 'secondBoxerRating14',
 'secondBoxerRecord14',
 'secondBoxerWeight14',
 'titles14',
 'date15',
 'firstBoxerRating15',
 'firstBoxerWeight15',
 'JudgeID15',
 'Links15',
 'location15',
 'metadata15',
 'numberofrounds15',
 'outcome15',
 'rating15',
 'referee15',
 'secondBoxer15',
 'secondBoxerLast615',
 'secondBoxerRating15',
 'secondBoxerRecord15',
 'secondBoxerWeight15',
 'titles15',
 'date16',
 'firstBoxerRating16',
 'firstBoxerWeight16',
 'JudgeID16',
 'Links16',
 'location16',
 'metadata16',
 'numberofrounds16',
 'outcome16',
 'rating16',
 'referee16',
 'secondBoxer16',
 'secondBoxerLast616',
 'secondBoxerRating16',
 'secondBoxerRecord16',
 'secondBoxerWeight16',
 'titles16',
 'date17',
 'firstBoxerRating17',
 'firstBoxerWeight17',
 'JudgeID17',
 'Links17',
 'location17',
 'metadata17',
 'numberofrounds17',
 'outcome17',
 'rating17',
 'referee17',
 'secondBoxer17',
 'secondBoxerLast617',
 'secondBoxerRating17',
 'secondBoxerRecord17',
 'secondBoxerWeight17',
 'titles17',
 'date18',
 'firstBoxerRating18',
 'firstBoxerWeight18',
 'JudgeID18',
 'Links18',
 'location18',
 'metadata18',
 'numberofrounds18',
 'outcome18',
 'rating18',
 'referee18',
 'secondBoxer18',
 'secondBoxerLast618',
 'secondBoxerRating18',
 'secondBoxerRecord18',
 'secondBoxerWeight18',
 'titles18',
 'date19',
 'firstBoxerRating19',
 'firstBoxerWeight19',
 'JudgeID19',
 'Links19',
 'location19',
 'metadata19',
 'numberofrounds19',
 'outcome19',
 'rating19',
 'referee19',
 'secondBoxer19',
 'secondBoxerLast619',
 'secondBoxerRating19',
 'secondBoxerRecord19',
 'secondBoxerWeight19',
 'titles19',
 'date20',
 'firstBoxerRating20',
 'firstBoxerWeight20',
 'JudgeID20',
 'Links20',
 'location20',
 'metadata20',
 'numberofrounds20',
 'outcome20',
 'rating20',
 'referee20',
 'secondBoxer20',
 'secondBoxerLast620',
 'secondBoxerRating20',
 'secondBoxerRecord20',
 'secondBoxerWeight20',
 'titles20',
 'date21',
 'firstBoxerRating21',
 'firstBoxerWeight21',
 'JudgeID21',
 'Links21',
 'location21',
 'metadata21',
 'numberofrounds21',
 'outcome21',
 'rating21',
 'referee21',
 'secondBoxer21',
 'secondBoxerLast621',
 'secondBoxerRating21',
 'secondBoxerRecord21',
 'secondBoxerWeight21',
 'titles21',
 'date22',
 'firstBoxerRating22',
 'firstBoxerWeight22',
 'JudgeID22',
 'Links22',
 'location22',
 'metadata22',
 'numberofrounds22',
 'outcome22',
 'rating22',
 'referee22',
 'secondBoxer22',
 'secondBoxerLast622',
 'secondBoxerRating22',
 'secondBoxerRecord22',
 'secondBoxerWeight22',
 'titles22',
 'date23',
 'firstBoxerRating23',
 'firstBoxerWeight23',
 'JudgeID23',
 'Links23',
 'location23',
 'metadata23',
 'numberofrounds23',
 'outcome23',
 'rating23',
 'referee23',
 'secondBoxer23',
 'secondBoxerLast623',
 'secondBoxerRating23',
 'secondBoxerRecord23',
 'secondBoxerWeight23',
 'titles23',
 'date24',
 'firstBoxerRating24',
 'firstBoxerWeight24',
 'JudgeID24',
 'Links24',
 'location24',
 'metadata24',
 'numberofrounds24',
 'outcome24',
 'rating24',
 'referee24',
 'secondBoxer24',
 'secondBoxerLast624',
 'secondBoxerRating24',
 'secondBoxerRecord24',
 'secondBoxerWeight24',
 'titles24',
 'date25',
 'firstBoxerRating25',
 'firstBoxerWeight25',
 'JudgeID25',
 'Links25',
 'location25',
 'metadata25',
 'numberofrounds25',
 'outcome25',
 'rating25',
 'referee25',
 'secondBoxer25',
 'secondBoxerLast625',
 'secondBoxerRating25',
 'secondBoxerRecord25',
 'secondBoxerWeight25',
 'titles25',
 'date26',
 'firstBoxerRating26',
 'firstBoxerWeight26',
 'JudgeID26',
 'Links26',
 'location26',
 'metadata26',
 'numberofrounds26',
 'outcome26',
 'rating26',
 'referee26',
 'secondBoxer26',
 'secondBoxerLast626',
 'secondBoxerRating26',
 'secondBoxerRecord26',
 'secondBoxerWeight26',
 'titles26',
 'date27',
 'firstBoxerRating27',
 'firstBoxerWeight27',
 'JudgeID27',
 'Links27',
 'location27',
 'metadata27',
 'numberofrounds27',
 'outcome27',
 'rating27',
 'referee27',
 'secondBoxer27',
 'secondBoxerLast627',
 'secondBoxerRating27',
 'secondBoxerRecord27',
 'secondBoxerWeight27',
 'titles27',
 'date28',
 'firstBoxerRating28',
 'firstBoxerWeight28',
 'JudgeID28',
 'Links28',
 'location28',
 'metadata28',
 'numberofrounds28',
 'outcome28',
 'rating28',
 'referee28',
 'secondBoxer28',
 'secondBoxerLast628',
 'secondBoxerRating28',
 'secondBoxerRecord28',
 'secondBoxerWeight28',
 'titles28',
 'date29',
 'firstBoxerRating29',
 'firstBoxerWeight29',
 'JudgeID29',
 'Links29',
 'location29',
 'metadata29',
 'numberofrounds29',
 'outcome29',
 'rating29',
 'referee29',
 'secondBoxer29',
 'secondBoxerLast629',
 'secondBoxerRating29',
 'secondBoxerRecord29',
 'secondBoxerWeight29',
 'titles29',
 'date30',
 'firstBoxerRating30',
 'firstBoxerWeight30',
 'JudgeID30',
 'Links30',
 'location30',
 'metadata30',
 'numberofrounds30',
 'outcome30',
 'rating30',
 'referee30',
 'secondBoxer30',
 'secondBoxerLast630',
 'secondBoxerRating30',
 'secondBoxerRecord30',
 'secondBoxerWeight30',
 'titles30',
 'date31',
 'firstBoxerRating31',
 'firstBoxerWeight31',
 'JudgeID31',
 'Links31',
 'location31',
 'metadata31',
 'numberofrounds31',
 'outcome31',
 'rating31',
 'referee31',
 'secondBoxer31',
 'secondBoxerLast631',
 'secondBoxerRating31',
 'secondBoxerRecord31',
 'secondBoxerWeight31',
 'titles31',
 'date32',
 'firstBoxerRating32',
 'firstBoxerWeight32',
 'JudgeID32',
 'Links32',
 'location32',
 'metadata32',
 'numberofrounds32',
 'outcome32',
 'rating32',
 'referee32',
 'secondBoxer32',
 'secondBoxerLast632',
 'secondBoxerRating32',
 'secondBoxerRecord32',
 'secondBoxerWeight32',
 'titles32',
 'date33',
 'firstBoxerRating33',
 'firstBoxerWeight33',
 'JudgeID33',
 'Links33',
 'location33',
 'metadata33',
 'numberofrounds33',
 'outcome33',
 'rating33',
 'referee33',
 'secondBoxer33',
 'secondBoxerLast633',
 'secondBoxerRating33',
 'secondBoxerRecord33',
 'secondBoxerWeight33',
 'titles33',
 'date34',
 'firstBoxerRating34',
 'firstBoxerWeight34',
 'JudgeID34',
 'Links34',
 'location34',
 'metadata34',
 'numberofrounds34',
 'outcome34',
 'rating34',
 'referee34',
 'secondBoxer34',
 'secondBoxerLast634',
 'secondBoxerRating34',
 'secondBoxerRecord34',
 'secondBoxerWeight34',
 'titles34',
 'date35',
 'firstBoxerRating35',
 'firstBoxerWeight35',
 'JudgeID35',
 'Links35',
 'location35',
 'metadata35',
 'numberofrounds35',
 'outcome35',
 'rating35',
 'referee35',
 'secondBoxer35',
 'secondBoxerLast635',
 'secondBoxerRating35',
 'secondBoxerRecord35',
 'secondBoxerWeight35',
 'titles35',
 'date36',
 'firstBoxerRating36',
 'firstBoxerWeight36',
 'JudgeID36',
 'Links36',
 'location36',
 'metadata36',
 'numberofrounds36',
 'outcome36',
 'rating36',
 'referee36',
 'secondBoxer36',
 'secondBoxerLast636',
 'secondBoxerRating36',
 'secondBoxerRecord36',
 'secondBoxerWeight36',
 'titles36',
 'date37',
 'firstBoxerRating37',
 'firstBoxerWeight37',
 'JudgeID37',
 'Links37',
 'location37',
 'metadata37',
 'numberofrounds37',
 'outcome37',
 'rating37',
 'referee37',
 'secondBoxer37',
 'secondBoxerLast637',
 'secondBoxerRating37',
 'secondBoxerRecord37',
 'secondBoxerWeight37',
 'titles37',
 'date38',
 'firstBoxerRating38',
 'firstBoxerWeight38',
 'JudgeID38',
 'Links38',
 'location38',
 'metadata38',
 'numberofrounds38',
 'outcome38',
 'rating38',
 'referee38',
 'secondBoxer38',
 'secondBoxerLast638',
 'secondBoxerRating38',
 'secondBoxerRecord38',
 'secondBoxerWeight38',
 'titles38',
 'date39',
 'firstBoxerRating39',
 'firstBoxerWeight39',
 'JudgeID39',
 'Links39',
 'location39',
 'metadata39',
 'numberofrounds39',
 'outcome39',
 'rating39',
 'referee39',
 'secondBoxer39',
 'secondBoxerLast639',
 'secondBoxerRating39',
 'secondBoxerRecord39',
 'secondBoxerWeight39',
 'titles39',
 'date40',
 'firstBoxerRating40',
 'firstBoxerWeight40',
 'JudgeID40',
 'Links40',
 'location40',
 'metadata40',
 'numberofrounds40',
 'outcome40',
 'rating40',
 'referee40',
 'secondBoxer40',
 'secondBoxerLast640',
 'secondBoxerRating40',
 'secondBoxerRecord40',
 'secondBoxerWeight40',
 'titles40',
 'date41',
 'firstBoxerRating41',
 'firstBoxerWeight41',
 'JudgeID41',
 'Links41',
 'location41',
 'metadata41',
 'numberofrounds41',
 'outcome41',
 'rating41',
 'referee41',
 'secondBoxer41',
 'secondBoxerLast641',
 'secondBoxerRating41',
 'secondBoxerRecord41',
 'secondBoxerWeight41',
 'titles41',
 'date42',
 'firstBoxerRating42',
 'firstBoxerWeight42',
 'JudgeID42',
 'Links42',
 'location42',
 'metadata42',
 'numberofrounds42',
 'outcome42',
 'rating42',
 'referee42',
 'secondBoxer42',
 'secondBoxerLast642',
 'secondBoxerRating42',
 'secondBoxerRecord42',
 'secondBoxerWeight42',
 'titles42',
 'date43',
 'firstBoxerRating43',
 'firstBoxerWeight43',
 'JudgeID43',
 'Links43',
 'location43',
 'metadata43',
 'numberofrounds43',
 'outcome43',
 'rating43',
 'referee43',
 'secondBoxer43',
 'secondBoxerLast643',
 'secondBoxerRating43',
 'secondBoxerRecord43',
 'secondBoxerWeight43',
 'titles43',
 'date44',
 'firstBoxerRating44',
 'firstBoxerWeight44',
 'JudgeID44',
 'Links44',
 'location44',
 'metadata44',
 'numberofrounds44',
 'outcome44',
 'rating44',
 'referee44',
 'secondBoxer44',
 'secondBoxerLast644',
 'secondBoxerRating44',
 'secondBoxerRecord44',
 'secondBoxerWeight44',
 'titles44',
 'date45',
 'firstBoxerRating45',
 'firstBoxerWeight45',
 'JudgeID45',
 'Links45',
 'location45',
 'metadata45',
 'numberofrounds45',
 'outcome45',
 'rating45',
 'referee45',
 'secondBoxer45',
 'secondBoxerLast645',
 'secondBoxerRating45',
 'secondBoxerRecord45',
 'secondBoxerWeight45',
 'titles45',
 'date46',
 'firstBoxerRating46',
 'firstBoxerWeight46',
 'JudgeID46',
 'Links46',
 'location46',
 'metadata46',
 'numberofrounds46',
 'outcome46',
 'rating46',
 'referee46',
 'secondBoxer46',
 'secondBoxerLast646',
 'secondBoxerRating46',
 'secondBoxerRecord46',
 'secondBoxerWeight46',
 'titles46',
 'date47',
 'firstBoxerRating47',
 'firstBoxerWeight47',
 'JudgeID47',
 'Links47',
 'location47',
 'metadata47',
 'numberofrounds47',
 'outcome47',
 'rating47',
 'referee47',
 'secondBoxer47',
 'secondBoxerLast647',
 'secondBoxerRating47',
 'secondBoxerRecord47',
 'secondBoxerWeight47',
 'titles47',
 'date48',
 'firstBoxerRating48',
 'firstBoxerWeight48',
 'JudgeID48',
 'Links48',
 'location48',
 'metadata48',
 'numberofrounds48',
 'outcome48',
 'rating48',
 'referee48',
 'secondBoxer48',
 'secondBoxerLast648',
 'secondBoxerRating48',
 'secondBoxerRecord48',
 'secondBoxerWeight48',
 'titles48',
 'date49',
 'firstBoxerRating49',
 'firstBoxerWeight49',
 'JudgeID49',
 'Links49',
 'location49',
 'metadata49',
 'numberofrounds49',
 'outcome49',
 'rating49',
 'referee49',
 'secondBoxer49',
 'secondBoxerLast649',
 'secondBoxerRating49',
 'secondBoxerRecord49',
 'secondBoxerWeight49',
 'titles49',
 'date50',
 'firstBoxerRating50',
 'firstBoxerWeight50',
 'JudgeID50',
 'Links50',
 'location50',
 'metadata50',
 'numberofrounds50',
 'outcome50',
 'rating50',
 'referee50',
 'secondBoxer50',
 'secondBoxerLast650',
 'secondBoxerRating50',
 'secondBoxerRecord50',
 'secondBoxerWeight50',
 'titles50',
 'date51',
 'firstBoxerRating51',
 'firstBoxerWeight51',
 'JudgeID51',
 'Links51',
 'location51',
 'metadata51',
 'numberofrounds51',
 'outcome51',
 'rating51',
 'referee51',
 'secondBoxer51',
 'secondBoxerLast651',
 'secondBoxerRating51',
 'secondBoxerRecord51',
 'secondBoxerWeight51',
 'titles51',
 'date52',
 'firstBoxerRating52',
 'firstBoxerWeight52',
 'JudgeID52',
 'Links52',
 'location52',
 'metadata52',
 'numberofrounds52',
 'outcome52',
 'rating52',
 'referee52',
 'secondBoxer52',
 'secondBoxerLast652',
 'secondBoxerRating52',
 'secondBoxerRecord52',
 'secondBoxerWeight52',
 'titles52',
 'date53',
 'firstBoxerRating53',
 'firstBoxerWeight53',
 'JudgeID53',
 'Links53',
 'location53',
 'metadata53',
 'numberofrounds53',
 'outcome53',
 'rating53',
 'referee53',
 'secondBoxer53',
 'secondBoxerLast653',
 'secondBoxerRating53',
 'secondBoxerRecord53',
 'secondBoxerWeight53',
 'titles53',
 'date54',
 'firstBoxerRating54',
 'firstBoxerWeight54',
 'JudgeID54',
 'Links54',
 'location54',
 'metadata54',
 'numberofrounds54',
 'outcome54',
 'rating54',
 'referee54',
 'secondBoxer54',
 'secondBoxerLast654',
 'secondBoxerRating54',
 'secondBoxerRecord54',
 'secondBoxerWeight54',
 'titles54',
 'date55',
 'firstBoxerRating55',
 'firstBoxerWeight55',
 'JudgeID55',
 'Links55',
 'location55',
 'metadata55',
 'numberofrounds55',
 'outcome55',
 'rating55',
 'referee55',
 'secondBoxer55',
 'secondBoxerLast655',
 'secondBoxerRating55',
 'secondBoxerRecord55',
 'secondBoxerWeight55',
 'titles55',
 'date56',
 'firstBoxerRating56',
 'firstBoxerWeight56',
 'JudgeID56',
 'Links56',
 'location56',
 'metadata56',
 'numberofrounds56',
 'outcome56',
 'rating56',
 'referee56',
 'secondBoxer56',
 'secondBoxerLast656',
 'secondBoxerRating56',
 'secondBoxerRecord56',
 'secondBoxerWeight56',
 'titles56',
 'date57',
 'firstBoxerRating57',
 'firstBoxerWeight57',
 'JudgeID57',
 'Links57',
 'location57',
 'metadata57',
 'numberofrounds57',
 'outcome57',
 'rating57',
 'referee57',
 'secondBoxer57',
 'secondBoxerLast657',
 'secondBoxerRating57',
 'secondBoxerRecord57',
 'secondBoxerWeight57',
 'titles57',
 'date58',
 'firstBoxerRating58',
 'firstBoxerWeight58',
 'JudgeID58',
 'Links58',
 'location58',
 'metadata58',
 'numberofrounds58',
 'outcome58',
 'rating58',
 'referee58',
 'secondBoxer58',
 'secondBoxerLast658',
 'secondBoxerRating58',
 'secondBoxerRecord58',
 'secondBoxerWeight58',
 'titles58',
 'date59',
 ...]

In [503]:
firstBoxer = ['firstBoxerWeight'+str(i) for i in range(1,85)]
secondBoxer = ['secondBoxerWeight'+str(i) for i in range(1,85)]
opp_rating = ['secondBoxerRating'+str(i) for i in range(1,85)]
data['average_weight'] = data[firstBoxer].mean(axis=1)
data['average_opponent_weight'] = data[secondBoxer].mean(axis=1)

In [595]:
def wins(col):
    return data[col].astype(str).str.extract('win(?P<win>.*?)}')
def draws(col):
    return data[col].astype(str).str.extract('draw(?P<draw>.*?)l')
def loss(col):
    return data[col].astype(str).str.extract('loss(?P<loss>.*?)w')
opp_rank = ['secondBoxerRecord'+str(i) for i in range(1,85)]
for i in opp_rank:
    data['opp_wins'+str(i)] = wins(i)
for i in opp_rank:
    data['opp_draws'+str(i)] = draws(i)
for i in opp_rank:
    data['opp_loss'+str(i)] = loss(i)

In [612]:
opp_drawsd = ['opp_draws'+str(i) for i in opp_rank]
# data[opp_drawsd] = data[opp_drawsd].apply(lambda x: x.str.replace('"',''))
opp_winsd = ['opp_wins'+str(i) for i in opp_rank]
data[opp_drawsd] = data[opp_drawsd].replace(regex='([a-zA-Z])', value=0)
data[opp_winsd] = data[opp_winsd].replace(regex='([a-zA-Z])', value=0)

In [654]:
data[opp_winsd] = data[opp_winsd].astype(float)*10
data[opp_drawsd] = data[opp_drawsd].astype(float)*5
data[opp_lossrd] = data[opp_lossrd].astype(float)*1
data['opp_points'] = data[opp_winsd].sum(axis=1) + data[opp_drawsd].sum(axis=1) 
data['opp_points'] = data['opp_win_points']/data['bouts_fought']

In [653]:
data['opp_win_points']/data['bouts_fought']

0       1.600000e+19
1       1.000000e+19
2       3.333333e+18
3       1.000000e+19
4       4.500001e+19
            ...
3840    7.500005e+18
3841    1.368750e+20
3842             NaN
3843             NaN
3844             NaN
Length: 3845, dtype: float64

In [667]:
nlat = data.nlargest(5,'opp_win_points').sort_values(by='opp_win_points', ascending=False)

In [668]:
nlat[['name','w','l','d','average_weight','average_opponent_weight']]

,name,w,l,d,average_weight,average_opponent_weight
3144,Denis Shafikov,40.0,4.0,2.0,139.091463,138.675000
2689,Robert Frankel,37.0,24.0,1.0,140.387500,140.575000
1421,Derrick Findley,32.0,27.0,1.0,165.537500,165.312500
1058,Kevin Johnson,34.0,16.0,1.0,244.355000,244.571429
3561,Jesus Soto Karass,29.0,13.0,4.0,148.798611,148.305556

In [699]:
merged2

,name,wins,draws,losses,location,division,average_weight,average_opponent_weight,win by knockout,win by split decision,win by technical knockout,win by unanimous decision
0,Roberto Salas,5.0,0.0,0.0,USA,cruiser,199.600000,206.800000,2.0,0.0,2.0,1.0
1,James Jackson,4.0,1.0,0.0,USA,heavy,231.750000,266.400000,1.0,0.0,1.0,2.0
2,Alex Love,3.0,0.0,0.0,USA,bantam,116.750000,118.000000,1.0,0.0,1.0,1.0
3,Juan Centeno,4.0,1.0,3.0,USA,fly,115.350000,112.950000,1.0,1.0,0.0,1.0
4,Jordan Weeks,2.0,0.0,0.0,USA,super middle,164.750000,162.250000,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
3840,Kawelo Alcos,2.0,2.0,0.0,"USA, Hawaii, Molokai",light fly,107.625000,107.812500,0.0,0.0,1.0,0.0
3841,Logan Yoon,16.0,0.0,0.0,"USA, Hawaii, Honolulu",welter,141.916667,139.783333,2.0,0.0,9.0,4.0
3842,NaN,NaN,NaN,NaN,NaN,unknown,155.052083,NaN,0.0,0.0,0.0,0.0
3843,NaN,NaN,NaN,NaN,NaN,unknown,148.480769,148.538462,1.0,0.0,4.0,1.0
3844,NaN,NaN,NaN,NaN,NaN,unknown,133.864035,134.188596,0.0,2.0,8.0,26.0

In [700]:
ref_outcome = ['referee'+str(i) for i in range(1,85)]
data = pd.concat([data,data[ref_outcome].astype(str).stack().str.replace('\[|\"','').str.extract('(\w+\s\w+)').groupby(level=0)[0].apply(pd.Series.value_counts).unstack(fill_value=0)],axis=1)
# for i in ref_outcome:
#     data[i] = data[i].str.findall('result:(?P<result>.*?)]')

In [701]:
data = data[['name','w','d','l','location','division','average_weight','average_opponent_weight','win KO','win SD', 'win TKO', 'win UD']]
# merged2 = merged2.rename(columns={'w':'wins','d':'draws','l':'losses','win KO':'win by knockout','win SD':'win by split decision','win TKO':'win by technical knockout','win UD':'win by unanimous decision'})

In [765]:
# long_data.merge(data['name'])
data

,Unnamed: 0,miles,location,name,sex,w,l,d,division,from,...,first83,second83,third83,first84,second84,third84,first85,second85,third85,bouts_fought
0,0,0.0,USA,Roberto Salas,male,5.0,0.0,0.0,cruiser,2016.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0
1,3,0.0,USA,James Jackson,male,4.0,0.0,1.0,heavy,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0
2,6,0.0,USA,Alex Love,female,3.0,0.0,0.0,bantam,2018.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
3,9,0.0,USA,Juan Centeno,male,4.0,3.0,1.0,fly,2016.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
4,12,0.0,USA,Jordan Weeks,male,2.0,0.0,0.0,super middle,2019.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3840,10116,4856.0,"USA, Hawaii, Molokai",Kawelo Alcos,male,2.0,0.0,2.0,light fly,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
3841,10118,4895.0,"USA, Hawaii, Honolulu",Logan Yoon,male,16.0,0.0,0.0,welter,2016.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0
3842,10120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unknown,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3843,11240,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unknown,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3844,11246,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unknown,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [704]:
data = pd.read_csv('C:\\Users\\User\\Documents\\visuals.csv')
data['division'] = data['division'].fillna('unknown')
data['bouts_fought'] = data['w'].astype('float')+data['l'].astype('float')+data['d'].astype('float')
WEIGHT_CLASS = data['division'].unique()
#uploading data for heatmap
long_data = pd.read_csv('C:\\Users\\User\\long_formadata.csv')
#count wins by stance
df = long_data[long_data['outcome'].str.contains('win',na=False)].groupby(['stance1', 'stance.y','division'])['outcome'].count().reset_index()
#count total fights by stance
df2 = long_data[['division','outcome']].groupby('division').count().reset_index()
df2.rename(columns={'outcome':'total'},inplace=True)
df = df.merge(df2,on='division')
#calculate wins in percentages
df['win_rate'] =df['outcome']/df['total'] *100
#filter out where stance1 is unknown
df = df[df.stance1 != 'unknown']
#cleaning data for top boxer table
firstBoxer = ['firstBoxerWeight'+str(i) for i in range(1,85)]
secondBoxer = ['secondBoxerWeight'+str(i) for i in range(1,85)]
opp_rating = ['secondBoxerRating'+str(i) for i in range(1,85)]
#average weight of boxer
data['average_weight'] = data[firstBoxer].mean(axis=1)
#average opponent weight
data['average_opponent_weight'] = data[secondBoxer].mean(axis=1)
#extract wins and losses
def wins(col):
    return data[col].astype(str).str.extract('win(?P<win>.*?)}')
def draws(col):
    return data[col].astype(str).str.extract('draw(?P<draw>.*?)l')
opp_rank = ['secondBoxerRecord'+str(i) for i in range(1,85)]
#update columns with wins and losses
for i in opp_rank:
    data['opp_wins'+str(i)] = wins(i)
for i in opp_rank:
    data['opp_draws'+str(i)] = draws(i)
opp_drawsd = ['opp_draws'+str(i) for i in opp_rank]
opp_winsd = ['opp_wins'+str(i) for i in opp_rank]
#remove quotation marks
data[opp_drawsd] = data[opp_drawsd].apply(lambda x: x.str.replace('"',''))
data[opp_winsd] = data[opp_drawsd].apply(lambda x: x.str.replace('"',''))
#replace all letters with number 0
data[opp_drawsd] = data[opp_drawsd].replace(regex='([a-zA-Z])', value=0)
data[opp_winsd] = data[opp_winsd].replace(regex='([a-zA-Z])', value=0)
#assume win is 10 points and draw is 5 points
data[opp_winsd] = data[opp_winsd].astype(float)*10
data[opp_drawsd] = data[opp_drawsd].astype(float)*5

In [705]:
#new column with total points
data['opp_points'] = data[opp_winsd].sum(axis=1) + data[opp_drawsd].sum(axis=1)
#divide points by number of bouts fought
data['opp_points'] = data['opp_points']/data['bouts_fought']

In [712]:
#get type of wins from referee column
ref_outcome = ['referee'+str(i) for i in range(1,85)]
topten = pd.concat([data,data[ref_outcome].astype(str).stack().str.replace('\[|\"','').str.extract('(\w+\s\w+)').groupby(level=0)[0].apply(pd.Series.value_counts).unstack(fill_value=0)],axis=1)
topten = topten[['name','w','d','l','location','division','average_weight','average_opponent_weight','opp_points','bouts_fought','win KO','win SD', 'win TKO', 'win UD']]
topten.rename(columns={'w':'wins','d':'draws','l':'losses','win KO':'win by knockout','win SD':'win by split decision','win TKO':'win by technical knockout','win UD':'win by unanimous decision'},inplace=True)
#limit to top 10

0       20.00
1       18.00
2       20.00
3       11.25
4       20.00
        ...
3840    15.00
3841    20.00
3842      NaN
3843      NaN
3844      NaN
Length: 3845, dtype: float64

In [1]:
data = pd.read_csv('C:\\Users\\User\\Documents\\visuals.csv')
data['division'] = data['division'].fillna('unknown')
data['bouts_fought'] = data['w'].astype('float')+data['l'].astype('float')+data['d'].astype('float')
WEIGHT_CLASS = data['division'].unique()
#uploading data for heatmap
long_data = pd.read_csv('C:\\Users\\User\\long_formadata.csv')
#count wins by stance

NameError: name 'pd' is not defined

In [751]:
long_data.merge()

,Unnamed: 0,name1,stance1,division,opponent,stance.y,outcome
0,0,Roberto Salas,southpaw,cruiser,Billy Martin,unknown,win
1,1,James Jackson,unknown,heavy,Billy Martin,unknown,win
2,2,Alex Love,orthodox,bantam,Billy Martin,unknown,win
3,3,Juan Centeno,unknown,fly,Mark Anderson,unknown,win
4,4,Jordan Weeks,unknown,super middle,Eddie Sisneros,unknown,win
...,...,...,...,...,...,...,...
325663,3872,Kawelo Alcos,unknown,light fly,NaN,NaN,NaN
325664,3873,Logan Yoon,unknown,welter,NaN,NaN,NaN
325665,3874,NaN,unknown,NaN,NaN,NaN,NaN
325666,3875,NaN,unknown,NaN,NaN,NaN,NaN
325667,3876,NaN,unknown,NaN,NaN,NaN,NaN

In [739]:
data[opp_winsd]
for i in opp_winsd:
    if

,opp_winssecondBoxerRecord1,opp_winssecondBoxerRecord2,opp_winssecondBoxerRecord3,opp_winssecondBoxerRecord4,opp_winssecondBoxerRecord5,opp_winssecondBoxerRecord6,opp_winssecondBoxerRecord7,opp_winssecondBoxerRecord8,opp_winssecondBoxerRecord9,opp_winssecondBoxerRecord10,...,opp_winssecondBoxerRecord75,opp_winssecondBoxerRecord76,opp_winssecondBoxerRecord77,opp_winssecondBoxerRecord78,opp_winssecondBoxerRecord79,opp_winssecondBoxerRecord80,opp_winssecondBoxerRecord81,opp_winssecondBoxerRecord82,opp_winssecondBoxerRecord83,opp_winssecondBoxerRecord84
0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,0.0,0.0,0.0,10.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3840,0.0,0.0,10.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3841,0.0,0.0,20.0,10.0,10.0,0.0,0.0,0.0,0.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3842,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3843,0.0,0.0,20.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3844,0.0,20.0,0.0,0.0,10.0,10.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [728]:
topten.nlargest()

,name,wins,draws,losses,location,division,average_weight,average_opponent_weight,opp_points,bouts_fought,win by knockout,win by split decision,win by technical knockout,win by unanimous decision
0,Roberto Salas,5.0,0.0,0.0,USA,cruiser,199.600000,206.800000,0.000,5.0,2.0,0.0,2.0,1.0
1,James Jackson,4.0,1.0,0.0,USA,heavy,231.750000,266.400000,3.000,5.0,1.0,0.0,1.0,2.0
2,Alex Love,3.0,0.0,0.0,USA,bantam,116.750000,118.000000,0.000,3.0,1.0,0.0,1.0,1.0
3,Juan Centeno,4.0,1.0,3.0,USA,fly,115.350000,112.950000,1.875,8.0,1.0,1.0,0.0,1.0
4,Jordan Weeks,2.0,0.0,0.0,USA,super middle,164.750000,162.250000,7.500,2.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3840,Kawelo Alcos,2.0,2.0,0.0,"USA, Hawaii, Molokai",light fly,107.625000,107.812500,3.750,4.0,0.0,0.0,1.0,0.0
3841,Logan Yoon,16.0,0.0,0.0,"USA, Hawaii, Honolulu",welter,141.916667,139.783333,11.250,16.0,2.0,0.0,9.0,4.0
3842,NaN,NaN,NaN,NaN,NaN,unknown,155.052083,NaN,NaN,NaN,0.0,0.0,0.0,0.0
3843,NaN,NaN,NaN,NaN,NaN,unknown,148.480769,148.538462,NaN,NaN,1.0,0.0,4.0,1.0
3844,NaN,NaN,NaN,NaN,NaN,unknown,133.864035,134.188596,NaN,NaN,0.0,2.0,8.0,26.0